// Code generated by ent, DO NOT EDIT.

package reconciliationusageextra

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the reconciliationusageextra type in the database.
	Label = "reconciliation_usage_extra"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldRuleProvider holds the string denoting the rule_provider field in the database.
	FieldRuleProvider = "rule_provider"
	// FieldRuleExternalKey holds the string denoting the rule_external_key field in the database.
	FieldRuleExternalKey = "rule_external_key"
	// FieldRuleVersion holds the string denoting the rule_version field in the database.
	FieldRuleVersion = "rule_version"
	// FieldRevenueOriginal holds the string denoting the revenue_original field in the database.
	FieldRevenueOriginal = "revenue_original"
	// FieldFxRateToCny holds the string denoting the fx_rate_to_cny field in the database.
	FieldFxRateToCny = "fx_rate_to_cny"
	// FieldRevenueCny holds the string denoting the revenue_cny field in the database.
	FieldRevenueCny = "revenue_cny"
	// FieldCollectedAt holds the string denoting the collected_at field in the database.
	FieldCollectedAt = "collected_at"
	// Table holds the table name of the reconciliationusageextra in the database.
	Table = "reconciliation_usage_extras"
)

// Columns holds all SQL columns for reconciliationusageextra fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUsageLogID,
	FieldAccountID,
	FieldRuleProvider,
	FieldRuleExternalKey,
	FieldRuleVersion,
	FieldRevenueOriginal,
	FieldFxRateToCny,
	FieldRevenueCny,
	FieldCollectedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRuleProvider holds the default value on creation for the "rule_provider" field.
	DefaultRuleProvider string
	// RuleProviderValidator is a validator for the "rule_provider" field. It is called by the builders before save.
	RuleProviderValidator func(string) error
	// DefaultRuleExternalKey holds the default value on creation for the "rule_external_key" field.
	DefaultRuleExternalKey string
	// RuleExternalKeyValidator is a validator for the "rule_external_key" field. It is called by the builders before save.
	RuleExternalKeyValidator func(string) error
	// DefaultRuleVersion holds the default value on creation for the "rule_version" field.
	DefaultRuleVersion int64
	// DefaultRevenueOriginal holds the default value on creation for the "revenue_original" field.
	DefaultRevenueOriginal float64
	// DefaultFxRateToCny holds the default value on creation for the "fx_rate_to_cny" field.
	DefaultFxRateToCny float64
	// DefaultRevenueCny holds the default value on creation for the "revenue_cny" field.
	DefaultRevenueCny float64
	// DefaultCollectedAt holds the default value on creation for the "collected_at" field.
	DefaultCollectedAt func() time.Time
)

// OrderOption defines the ordering options for the ReconciliationUsageExtra queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByRuleProvider orders the results by the rule_provider field.
func ByRuleProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleProvider, opts...).ToFunc()
}

// ByRuleExternalKey orders the results by the rule_external_key field.
func ByRuleExternalKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleExternalKey, opts...).ToFunc()
}

// ByRuleVersion orders the results by the rule_version field.
func ByRuleVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleVersion, opts...).ToFunc()
}

// ByRevenueOriginal orders the results by the revenue_original field.
func ByRevenueOriginal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenueOriginal, opts...).ToFunc()
}

// ByFxRateToCny orders the results by the fx_rate_to_cny field.
func ByFxRateToCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFxRateToCny, opts...).ToFunc()
}

// ByRevenueCny orders the results by the revenue_cny field.
func ByRevenueCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenueCny, opts...).ToFunc()
}

// ByCollectedAt orders the results by the collected_at field.
func ByCollectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectedAt, opts...).ToFunc()
}
