// Code generated by ent, DO NOT EDIT.

package reconciliationusageextra

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldUpdatedAt, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldUsageLogID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldAccountID, v))
}

// RuleProvider applies equality check predicate on the "rule_provider" field. It's identical to RuleProviderEQ.
func RuleProvider(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRuleProvider, v))
}

// RuleExternalKey applies equality check predicate on the "rule_external_key" field. It's identical to RuleExternalKeyEQ.
func RuleExternalKey(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRuleExternalKey, v))
}

// RuleVersion applies equality check predicate on the "rule_version" field. It's identical to RuleVersionEQ.
func RuleVersion(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRuleVersion, v))
}

// RevenueOriginal applies equality check predicate on the "revenue_original" field. It's identical to RevenueOriginalEQ.
func RevenueOriginal(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRevenueOriginal, v))
}

// FxRateToCny applies equality check predicate on the "fx_rate_to_cny" field. It's identical to FxRateToCnyEQ.
func FxRateToCny(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldFxRateToCny, v))
}

// RevenueCny applies equality check predicate on the "revenue_cny" field. It's identical to RevenueCnyEQ.
func RevenueCny(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRevenueCny, v))
}

// CollectedAt applies equality check predicate on the "collected_at" field. It's identical to CollectedAtEQ.
func CollectedAt(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldCollectedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldUpdatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldUsageLogID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldAccountID, v))
}

// RuleProviderEQ applies the EQ predicate on the "rule_provider" field.
func RuleProviderEQ(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRuleProvider, v))
}

// RuleProviderNEQ applies the NEQ predicate on the "rule_provider" field.
func RuleProviderNEQ(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldRuleProvider, v))
}

// RuleProviderIn applies the In predicate on the "rule_provider" field.
func RuleProviderIn(vs ...string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldRuleProvider, vs...))
}

// RuleProviderNotIn applies the NotIn predicate on the "rule_provider" field.
func RuleProviderNotIn(vs ...string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldRuleProvider, vs...))
}

// RuleProviderGT applies the GT predicate on the "rule_provider" field.
func RuleProviderGT(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldRuleProvider, v))
}

// RuleProviderGTE applies the GTE predicate on the "rule_provider" field.
func RuleProviderGTE(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldRuleProvider, v))
}

// RuleProviderLT applies the LT predicate on the "rule_provider" field.
func RuleProviderLT(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldRuleProvider, v))
}

// RuleProviderLTE applies the LTE predicate on the "rule_provider" field.
func RuleProviderLTE(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldRuleProvider, v))
}

// RuleProviderContains applies the Contains predicate on the "rule_provider" field.
func RuleProviderContains(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldContains(FieldRuleProvider, v))
}

// RuleProviderHasPrefix applies the HasPrefix predicate on the "rule_provider" field.
func RuleProviderHasPrefix(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldHasPrefix(FieldRuleProvider, v))
}

// RuleProviderHasSuffix applies the HasSuffix predicate on the "rule_provider" field.
func RuleProviderHasSuffix(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldHasSuffix(FieldRuleProvider, v))
}

// RuleProviderEqualFold applies the EqualFold predicate on the "rule_provider" field.
func RuleProviderEqualFold(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEqualFold(FieldRuleProvider, v))
}

// RuleProviderContainsFold applies the ContainsFold predicate on the "rule_provider" field.
func RuleProviderContainsFold(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldContainsFold(FieldRuleProvider, v))
}

// RuleExternalKeyEQ applies the EQ predicate on the "rule_external_key" field.
func RuleExternalKeyEQ(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRuleExternalKey, v))
}

// RuleExternalKeyNEQ applies the NEQ predicate on the "rule_external_key" field.
func RuleExternalKeyNEQ(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldRuleExternalKey, v))
}

// RuleExternalKeyIn applies the In predicate on the "rule_external_key" field.
func RuleExternalKeyIn(vs ...string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldRuleExternalKey, vs...))
}

// RuleExternalKeyNotIn applies the NotIn predicate on the "rule_external_key" field.
func RuleExternalKeyNotIn(vs ...string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldRuleExternalKey, vs...))
}

// RuleExternalKeyGT applies the GT predicate on the "rule_external_key" field.
func RuleExternalKeyGT(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldRuleExternalKey, v))
}

// RuleExternalKeyGTE applies the GTE predicate on the "rule_external_key" field.
func RuleExternalKeyGTE(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldRuleExternalKey, v))
}

// RuleExternalKeyLT applies the LT predicate on the "rule_external_key" field.
func RuleExternalKeyLT(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldRuleExternalKey, v))
}

// RuleExternalKeyLTE applies the LTE predicate on the "rule_external_key" field.
func RuleExternalKeyLTE(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldRuleExternalKey, v))
}

// RuleExternalKeyContains applies the Contains predicate on the "rule_external_key" field.
func RuleExternalKeyContains(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldContains(FieldRuleExternalKey, v))
}

// RuleExternalKeyHasPrefix applies the HasPrefix predicate on the "rule_external_key" field.
func RuleExternalKeyHasPrefix(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldHasPrefix(FieldRuleExternalKey, v))
}

// RuleExternalKeyHasSuffix applies the HasSuffix predicate on the "rule_external_key" field.
func RuleExternalKeyHasSuffix(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldHasSuffix(FieldRuleExternalKey, v))
}

// RuleExternalKeyEqualFold applies the EqualFold predicate on the "rule_external_key" field.
func RuleExternalKeyEqualFold(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEqualFold(FieldRuleExternalKey, v))
}

// RuleExternalKeyContainsFold applies the ContainsFold predicate on the "rule_external_key" field.
func RuleExternalKeyContainsFold(v string) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldContainsFold(FieldRuleExternalKey, v))
}

// RuleVersionEQ applies the EQ predicate on the "rule_version" field.
func RuleVersionEQ(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRuleVersion, v))
}

// RuleVersionNEQ applies the NEQ predicate on the "rule_version" field.
func RuleVersionNEQ(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldRuleVersion, v))
}

// RuleVersionIn applies the In predicate on the "rule_version" field.
func RuleVersionIn(vs ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldRuleVersion, vs...))
}

// RuleVersionNotIn applies the NotIn predicate on the "rule_version" field.
func RuleVersionNotIn(vs ...int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldRuleVersion, vs...))
}

// RuleVersionGT applies the GT predicate on the "rule_version" field.
func RuleVersionGT(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldRuleVersion, v))
}

// RuleVersionGTE applies the GTE predicate on the "rule_version" field.
func RuleVersionGTE(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldRuleVersion, v))
}

// RuleVersionLT applies the LT predicate on the "rule_version" field.
func RuleVersionLT(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldRuleVersion, v))
}

// RuleVersionLTE applies the LTE predicate on the "rule_version" field.
func RuleVersionLTE(v int64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldRuleVersion, v))
}

// RevenueOriginalEQ applies the EQ predicate on the "revenue_original" field.
func RevenueOriginalEQ(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRevenueOriginal, v))
}

// RevenueOriginalNEQ applies the NEQ predicate on the "revenue_original" field.
func RevenueOriginalNEQ(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldRevenueOriginal, v))
}

// RevenueOriginalIn applies the In predicate on the "revenue_original" field.
func RevenueOriginalIn(vs ...float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldRevenueOriginal, vs...))
}

// RevenueOriginalNotIn applies the NotIn predicate on the "revenue_original" field.
func RevenueOriginalNotIn(vs ...float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldRevenueOriginal, vs...))
}

// RevenueOriginalGT applies the GT predicate on the "revenue_original" field.
func RevenueOriginalGT(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldRevenueOriginal, v))
}

// RevenueOriginalGTE applies the GTE predicate on the "revenue_original" field.
func RevenueOriginalGTE(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldRevenueOriginal, v))
}

// RevenueOriginalLT applies the LT predicate on the "revenue_original" field.
func RevenueOriginalLT(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldRevenueOriginal, v))
}

// RevenueOriginalLTE applies the LTE predicate on the "revenue_original" field.
func RevenueOriginalLTE(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldRevenueOriginal, v))
}

// FxRateToCnyEQ applies the EQ predicate on the "fx_rate_to_cny" field.
func FxRateToCnyEQ(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldFxRateToCny, v))
}

// FxRateToCnyNEQ applies the NEQ predicate on the "fx_rate_to_cny" field.
func FxRateToCnyNEQ(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldFxRateToCny, v))
}

// FxRateToCnyIn applies the In predicate on the "fx_rate_to_cny" field.
func FxRateToCnyIn(vs ...float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldFxRateToCny, vs...))
}

// FxRateToCnyNotIn applies the NotIn predicate on the "fx_rate_to_cny" field.
func FxRateToCnyNotIn(vs ...float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldFxRateToCny, vs...))
}

// FxRateToCnyGT applies the GT predicate on the "fx_rate_to_cny" field.
func FxRateToCnyGT(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldFxRateToCny, v))
}

// FxRateToCnyGTE applies the GTE predicate on the "fx_rate_to_cny" field.
func FxRateToCnyGTE(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldFxRateToCny, v))
}

// FxRateToCnyLT applies the LT predicate on the "fx_rate_to_cny" field.
func FxRateToCnyLT(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldFxRateToCny, v))
}

// FxRateToCnyLTE applies the LTE predicate on the "fx_rate_to_cny" field.
func FxRateToCnyLTE(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldFxRateToCny, v))
}

// RevenueCnyEQ applies the EQ predicate on the "revenue_cny" field.
func RevenueCnyEQ(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldRevenueCny, v))
}

// RevenueCnyNEQ applies the NEQ predicate on the "revenue_cny" field.
func RevenueCnyNEQ(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldRevenueCny, v))
}

// RevenueCnyIn applies the In predicate on the "revenue_cny" field.
func RevenueCnyIn(vs ...float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldRevenueCny, vs...))
}

// RevenueCnyNotIn applies the NotIn predicate on the "revenue_cny" field.
func RevenueCnyNotIn(vs ...float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldRevenueCny, vs...))
}

// RevenueCnyGT applies the GT predicate on the "revenue_cny" field.
func RevenueCnyGT(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldRevenueCny, v))
}

// RevenueCnyGTE applies the GTE predicate on the "revenue_cny" field.
func RevenueCnyGTE(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldRevenueCny, v))
}

// RevenueCnyLT applies the LT predicate on the "revenue_cny" field.
func RevenueCnyLT(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldRevenueCny, v))
}

// RevenueCnyLTE applies the LTE predicate on the "revenue_cny" field.
func RevenueCnyLTE(v float64) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldRevenueCny, v))
}

// CollectedAtEQ applies the EQ predicate on the "collected_at" field.
func CollectedAtEQ(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldEQ(FieldCollectedAt, v))
}

// CollectedAtNEQ applies the NEQ predicate on the "collected_at" field.
func CollectedAtNEQ(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNEQ(FieldCollectedAt, v))
}

// CollectedAtIn applies the In predicate on the "collected_at" field.
func CollectedAtIn(vs ...time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldIn(FieldCollectedAt, vs...))
}

// CollectedAtNotIn applies the NotIn predicate on the "collected_at" field.
func CollectedAtNotIn(vs ...time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldNotIn(FieldCollectedAt, vs...))
}

// CollectedAtGT applies the GT predicate on the "collected_at" field.
func CollectedAtGT(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGT(FieldCollectedAt, v))
}

// CollectedAtGTE applies the GTE predicate on the "collected_at" field.
func CollectedAtGTE(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldGTE(FieldCollectedAt, v))
}

// CollectedAtLT applies the LT predicate on the "collected_at" field.
func CollectedAtLT(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLT(FieldCollectedAt, v))
}

// CollectedAtLTE applies the LTE predicate on the "collected_at" field.
func CollectedAtLTE(v time.Time) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.FieldLTE(FieldCollectedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReconciliationUsageExtra) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReconciliationUsageExtra) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReconciliationUsageExtra) predicate.ReconciliationUsageExtra {
	return predicate.ReconciliationUsageExtra(sql.NotPredicates(p))
}
