// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationaccountrule"
)

// ReconciliationAccountRuleUpdate is the builder for updating ReconciliationAccountRule entities.
type ReconciliationAccountRuleUpdate struct {
	config
	hooks    []Hook
	mutation *ReconciliationAccountRuleMutation
}

// Where appends a list predicates to the ReconciliationAccountRuleUpdate builder.
func (_u *ReconciliationAccountRuleUpdate) Where(ps ...predicate.ReconciliationAccountRule) *ReconciliationAccountRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationAccountRuleUpdate) SetUpdatedAt(v time.Time) *ReconciliationAccountRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ReconciliationAccountRuleUpdate) SetAccountID(v int64) *ReconciliationAccountRuleUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdate) SetNillableAccountID(v *int64) *ReconciliationAccountRuleUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ReconciliationAccountRuleUpdate) AddAccountID(v int64) *ReconciliationAccountRuleUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ReconciliationAccountRuleUpdate) SetProvider(v string) *ReconciliationAccountRuleUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdate) SetNillableProvider(v *string) *ReconciliationAccountRuleUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetExternalKey sets the "external_key" field.
func (_u *ReconciliationAccountRuleUpdate) SetExternalKey(v string) *ReconciliationAccountRuleUpdate {
	_u.mutation.SetExternalKey(v)
	return _u
}

// SetNillableExternalKey sets the "external_key" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdate) SetNillableExternalKey(v *string) *ReconciliationAccountRuleUpdate {
	if v != nil {
		_u.SetExternalKey(*v)
	}
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *ReconciliationAccountRuleUpdate) SetMultiplier(v float64) *ReconciliationAccountRuleUpdate {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdate) SetNillableMultiplier(v *float64) *ReconciliationAccountRuleUpdate {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *ReconciliationAccountRuleUpdate) AddMultiplier(v float64) *ReconciliationAccountRuleUpdate {
	_u.mutation.AddMultiplier(v)
	return _u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (_u *ReconciliationAccountRuleUpdate) ClearMultiplier() *ReconciliationAccountRuleUpdate {
	_u.mutation.ClearMultiplier()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ReconciliationAccountRuleUpdate) SetVersion(v int64) *ReconciliationAccountRuleUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdate) SetNillableVersion(v *int64) *ReconciliationAccountRuleUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ReconciliationAccountRuleUpdate) AddVersion(v int64) *ReconciliationAccountRuleUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ReconciliationAccountRuleUpdate) SetEnabled(v bool) *ReconciliationAccountRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdate) SetNillableEnabled(v *bool) *ReconciliationAccountRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ReconciliationAccountRuleMutation object of the builder.
func (_u *ReconciliationAccountRuleUpdate) Mutation() *ReconciliationAccountRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReconciliationAccountRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationAccountRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReconciliationAccountRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationAccountRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationAccountRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationaccountrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationAccountRuleUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := reconciliationaccountrule.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationAccountRule.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalKey(); ok {
		if err := reconciliationaccountrule.ExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "external_key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationAccountRule.external_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationAccountRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationaccountrule.Table, reconciliationaccountrule.Columns, sqlgraph.NewFieldSpec(reconciliationaccountrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationaccountrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(reconciliationaccountrule.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(reconciliationaccountrule.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(reconciliationaccountrule.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalKey(); ok {
		_spec.SetField(reconciliationaccountrule.FieldExternalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MultiplierCleared() {
		_spec.ClearField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(reconciliationaccountrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(reconciliationaccountrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(reconciliationaccountrule.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationaccountrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReconciliationAccountRuleUpdateOne is the builder for updating a single ReconciliationAccountRule entity.
type ReconciliationAccountRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReconciliationAccountRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetUpdatedAt(v time.Time) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetAccountID(v int64) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdateOne) SetNillableAccountID(v *int64) *ReconciliationAccountRuleUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ReconciliationAccountRuleUpdateOne) AddAccountID(v int64) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetProvider(v string) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdateOne) SetNillableProvider(v *string) *ReconciliationAccountRuleUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetExternalKey sets the "external_key" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetExternalKey(v string) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.SetExternalKey(v)
	return _u
}

// SetNillableExternalKey sets the "external_key" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdateOne) SetNillableExternalKey(v *string) *ReconciliationAccountRuleUpdateOne {
	if v != nil {
		_u.SetExternalKey(*v)
	}
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetMultiplier(v float64) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdateOne) SetNillableMultiplier(v *float64) *ReconciliationAccountRuleUpdateOne {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *ReconciliationAccountRuleUpdateOne) AddMultiplier(v float64) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.AddMultiplier(v)
	return _u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (_u *ReconciliationAccountRuleUpdateOne) ClearMultiplier() *ReconciliationAccountRuleUpdateOne {
	_u.mutation.ClearMultiplier()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetVersion(v int64) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdateOne) SetNillableVersion(v *int64) *ReconciliationAccountRuleUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ReconciliationAccountRuleUpdateOne) AddVersion(v int64) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ReconciliationAccountRuleUpdateOne) SetEnabled(v bool) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ReconciliationAccountRuleUpdateOne) SetNillableEnabled(v *bool) *ReconciliationAccountRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ReconciliationAccountRuleMutation object of the builder.
func (_u *ReconciliationAccountRuleUpdateOne) Mutation() *ReconciliationAccountRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReconciliationAccountRuleUpdate builder.
func (_u *ReconciliationAccountRuleUpdateOne) Where(ps ...predicate.ReconciliationAccountRule) *ReconciliationAccountRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReconciliationAccountRuleUpdateOne) Select(field string, fields ...string) *ReconciliationAccountRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReconciliationAccountRule entity.
func (_u *ReconciliationAccountRuleUpdateOne) Save(ctx context.Context) (*ReconciliationAccountRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationAccountRuleUpdateOne) SaveX(ctx context.Context) *ReconciliationAccountRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReconciliationAccountRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationAccountRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationAccountRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationaccountrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationAccountRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := reconciliationaccountrule.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationAccountRule.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalKey(); ok {
		if err := reconciliationaccountrule.ExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "external_key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationAccountRule.external_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationAccountRuleUpdateOne) sqlSave(ctx context.Context) (_node *ReconciliationAccountRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationaccountrule.Table, reconciliationaccountrule.Columns, sqlgraph.NewFieldSpec(reconciliationaccountrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReconciliationAccountRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reconciliationaccountrule.FieldID)
		for _, f := range fields {
			if !reconciliationaccountrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reconciliationaccountrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationaccountrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(reconciliationaccountrule.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(reconciliationaccountrule.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(reconciliationaccountrule.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalKey(); ok {
		_spec.SetField(reconciliationaccountrule.FieldExternalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MultiplierCleared() {
		_spec.ClearField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(reconciliationaccountrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(reconciliationaccountrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(reconciliationaccountrule.FieldEnabled, field.TypeBool, value)
	}
	_node = &ReconciliationAccountRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationaccountrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
