// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationaccountrule"
)

// ReconciliationAccountRule is the model entity for the ReconciliationAccountRule schema.
type ReconciliationAccountRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 本站账号 ID
	AccountID int64 `json:"account_id,omitempty"`
	// 上游提供方，目前只支持 a6
	Provider string `json:"provider,omitempty"`
	// 上游令牌名（A6 的 token_name）
	ExternalKey string `json:"external_key,omitempty"`
	// 预留字段：账号计费倍率。当前对账口径不使用
	Multiplier *float64 `json:"multiplier,omitempty"`
	// 规则版本号，每次保存自增
	Version int64 `json:"version,omitempty"`
	// 是否启用该规则
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReconciliationAccountRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reconciliationaccountrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case reconciliationaccountrule.FieldMultiplier:
			values[i] = new(sql.NullFloat64)
		case reconciliationaccountrule.FieldID, reconciliationaccountrule.FieldAccountID, reconciliationaccountrule.FieldVersion:
			values[i] = new(sql.NullInt64)
		case reconciliationaccountrule.FieldProvider, reconciliationaccountrule.FieldExternalKey:
			values[i] = new(sql.NullString)
		case reconciliationaccountrule.FieldCreatedAt, reconciliationaccountrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReconciliationAccountRule fields.
func (_m *ReconciliationAccountRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reconciliationaccountrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case reconciliationaccountrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reconciliationaccountrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case reconciliationaccountrule.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case reconciliationaccountrule.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case reconciliationaccountrule.FieldExternalKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_key", values[i])
			} else if value.Valid {
				_m.ExternalKey = value.String
			}
		case reconciliationaccountrule.FieldMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field multiplier", values[i])
			} else if value.Valid {
				_m.Multiplier = new(float64)
				*_m.Multiplier = value.Float64
			}
		case reconciliationaccountrule.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case reconciliationaccountrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReconciliationAccountRule.
// This includes values selected through modifiers, order, etc.
func (_m *ReconciliationAccountRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReconciliationAccountRule.
// Note that you need to call ReconciliationAccountRule.Unwrap() before calling this method if this ReconciliationAccountRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReconciliationAccountRule) Update() *ReconciliationAccountRuleUpdateOne {
	return NewReconciliationAccountRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReconciliationAccountRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReconciliationAccountRule) Unwrap() *ReconciliationAccountRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReconciliationAccountRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReconciliationAccountRule) String() string {
	var builder strings.Builder
	builder.WriteString("ReconciliationAccountRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("external_key=")
	builder.WriteString(_m.ExternalKey)
	builder.WriteString(", ")
	if v := _m.Multiplier; v != nil {
		builder.WriteString("multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// ReconciliationAccountRules is a parsable slice of ReconciliationAccountRule.
type ReconciliationAccountRules []*ReconciliationAccountRule
