// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationsyncstate"
)

// ReconciliationSyncStateDelete is the builder for deleting a ReconciliationSyncState entity.
type ReconciliationSyncStateDelete struct {
	config
	hooks    []Hook
	mutation *ReconciliationSyncStateMutation
}

// Where appends a list predicates to the ReconciliationSyncStateDelete builder.
func (_d *ReconciliationSyncStateDelete) Where(ps ...predicate.ReconciliationSyncState) *ReconciliationSyncStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ReconciliationSyncStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReconciliationSyncStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ReconciliationSyncStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reconciliationsyncstate.Table, sqlgraph.NewFieldSpec(reconciliationsyncstate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ReconciliationSyncStateDeleteOne is the builder for deleting a single ReconciliationSyncState entity.
type ReconciliationSyncStateDeleteOne struct {
	_d *ReconciliationSyncStateDelete
}

// Where appends a list predicates to the ReconciliationSyncStateDelete builder.
func (_d *ReconciliationSyncStateDeleteOne) Where(ps ...predicate.ReconciliationSyncState) *ReconciliationSyncStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ReconciliationSyncStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reconciliationsyncstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReconciliationSyncStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
