// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationaccountrule"
)

// ReconciliationAccountRuleCreate is the builder for creating a ReconciliationAccountRule entity.
type ReconciliationAccountRuleCreate struct {
	config
	mutation *ReconciliationAccountRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReconciliationAccountRuleCreate) SetCreatedAt(v time.Time) *ReconciliationAccountRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableCreatedAt(v *time.Time) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReconciliationAccountRuleCreate) SetUpdatedAt(v time.Time) *ReconciliationAccountRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableUpdatedAt(v *time.Time) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ReconciliationAccountRuleCreate) SetAccountID(v int64) *ReconciliationAccountRuleCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ReconciliationAccountRuleCreate) SetProvider(v string) *ReconciliationAccountRuleCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableProvider(v *string) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetExternalKey sets the "external_key" field.
func (_c *ReconciliationAccountRuleCreate) SetExternalKey(v string) *ReconciliationAccountRuleCreate {
	_c.mutation.SetExternalKey(v)
	return _c
}

// SetNillableExternalKey sets the "external_key" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableExternalKey(v *string) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetExternalKey(*v)
	}
	return _c
}

// SetMultiplier sets the "multiplier" field.
func (_c *ReconciliationAccountRuleCreate) SetMultiplier(v float64) *ReconciliationAccountRuleCreate {
	_c.mutation.SetMultiplier(v)
	return _c
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableMultiplier(v *float64) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetMultiplier(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ReconciliationAccountRuleCreate) SetVersion(v int64) *ReconciliationAccountRuleCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableVersion(v *int64) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ReconciliationAccountRuleCreate) SetEnabled(v bool) *ReconciliationAccountRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ReconciliationAccountRuleCreate) SetNillableEnabled(v *bool) *ReconciliationAccountRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// Mutation returns the ReconciliationAccountRuleMutation object of the builder.
func (_c *ReconciliationAccountRuleCreate) Mutation() *ReconciliationAccountRuleMutation {
	return _c.mutation
}

// Save creates the ReconciliationAccountRule in the database.
func (_c *ReconciliationAccountRuleCreate) Save(ctx context.Context) (*ReconciliationAccountRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReconciliationAccountRuleCreate) SaveX(ctx context.Context) *ReconciliationAccountRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationAccountRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationAccountRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReconciliationAccountRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reconciliationaccountrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := reconciliationaccountrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := reconciliationaccountrule.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.ExternalKey(); !ok {
		v := reconciliationaccountrule.DefaultExternalKey
		_c.mutation.SetExternalKey(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := reconciliationaccountrule.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := reconciliationaccountrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReconciliationAccountRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReconciliationAccountRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReconciliationAccountRule.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ReconciliationAccountRule.account_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ReconciliationAccountRule.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := reconciliationaccountrule.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationAccountRule.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalKey(); !ok {
		return &ValidationError{Name: "external_key", err: errors.New(`ent: missing required field "ReconciliationAccountRule.external_key"`)}
	}
	if v, ok := _c.mutation.ExternalKey(); ok {
		if err := reconciliationaccountrule.ExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "external_key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationAccountRule.external_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ReconciliationAccountRule.version"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ReconciliationAccountRule.enabled"`)}
	}
	return nil
}

func (_c *ReconciliationAccountRuleCreate) sqlSave(ctx context.Context) (*ReconciliationAccountRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReconciliationAccountRuleCreate) createSpec() (*ReconciliationAccountRule, *sqlgraph.CreateSpec) {
	var (
		_node = &ReconciliationAccountRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reconciliationaccountrule.Table, sqlgraph.NewFieldSpec(reconciliationaccountrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reconciliationaccountrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationaccountrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(reconciliationaccountrule.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(reconciliationaccountrule.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ExternalKey(); ok {
		_spec.SetField(reconciliationaccountrule.FieldExternalKey, field.TypeString, value)
		_node.ExternalKey = value
	}
	if value, ok := _c.mutation.Multiplier(); ok {
		_spec.SetField(reconciliationaccountrule.FieldMultiplier, field.TypeFloat64, value)
		_node.Multiplier = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(reconciliationaccountrule.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(reconciliationaccountrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReconciliationAccountRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReconciliationAccountRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReconciliationAccountRuleCreate) OnConflict(opts ...sql.ConflictOption) *ReconciliationAccountRuleUpsertOne {
	_c.conflict = opts
	return &ReconciliationAccountRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReconciliationAccountRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReconciliationAccountRuleCreate) OnConflictColumns(columns ...string) *ReconciliationAccountRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReconciliationAccountRuleUpsertOne{
		create: _c,
	}
}

type (
	// ReconciliationAccountRuleUpsertOne is the builder for "upsert"-ing
	//  one ReconciliationAccountRule node.
	ReconciliationAccountRuleUpsertOne struct {
		create *ReconciliationAccountRuleCreate
	}

	// ReconciliationAccountRuleUpsert is the "OnConflict" setter.
	ReconciliationAccountRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationAccountRuleUpsert) SetUpdatedAt(v time.Time) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateUpdatedAt() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ReconciliationAccountRuleUpsert) SetAccountID(v int64) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateAccountID() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ReconciliationAccountRuleUpsert) AddAccountID(v int64) *ReconciliationAccountRuleUpsert {
	u.Add(reconciliationaccountrule.FieldAccountID, v)
	return u
}

// SetProvider sets the "provider" field.
func (u *ReconciliationAccountRuleUpsert) SetProvider(v string) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateProvider() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldProvider)
	return u
}

// SetExternalKey sets the "external_key" field.
func (u *ReconciliationAccountRuleUpsert) SetExternalKey(v string) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldExternalKey, v)
	return u
}

// UpdateExternalKey sets the "external_key" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateExternalKey() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldExternalKey)
	return u
}

// SetMultiplier sets the "multiplier" field.
func (u *ReconciliationAccountRuleUpsert) SetMultiplier(v float64) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldMultiplier, v)
	return u
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateMultiplier() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldMultiplier)
	return u
}

// AddMultiplier adds v to the "multiplier" field.
func (u *ReconciliationAccountRuleUpsert) AddMultiplier(v float64) *ReconciliationAccountRuleUpsert {
	u.Add(reconciliationaccountrule.FieldMultiplier, v)
	return u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (u *ReconciliationAccountRuleUpsert) ClearMultiplier() *ReconciliationAccountRuleUpsert {
	u.SetNull(reconciliationaccountrule.FieldMultiplier)
	return u
}

// SetVersion sets the "version" field.
func (u *ReconciliationAccountRuleUpsert) SetVersion(v int64) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateVersion() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ReconciliationAccountRuleUpsert) AddVersion(v int64) *ReconciliationAccountRuleUpsert {
	u.Add(reconciliationaccountrule.FieldVersion, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ReconciliationAccountRuleUpsert) SetEnabled(v bool) *ReconciliationAccountRuleUpsert {
	u.Set(reconciliationaccountrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsert) UpdateEnabled() *ReconciliationAccountRuleUpsert {
	u.SetExcluded(reconciliationaccountrule.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReconciliationAccountRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReconciliationAccountRuleUpsertOne) UpdateNewValues() *ReconciliationAccountRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(reconciliationaccountrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReconciliationAccountRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReconciliationAccountRuleUpsertOne) Ignore() *ReconciliationAccountRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReconciliationAccountRuleUpsertOne) DoNothing() *ReconciliationAccountRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReconciliationAccountRuleCreate.OnConflict
// documentation for more info.
func (u *ReconciliationAccountRuleUpsertOne) Update(set func(*ReconciliationAccountRuleUpsert)) *ReconciliationAccountRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReconciliationAccountRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationAccountRuleUpsertOne) SetUpdatedAt(v time.Time) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateUpdatedAt() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ReconciliationAccountRuleUpsertOne) SetAccountID(v int64) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ReconciliationAccountRuleUpsertOne) AddAccountID(v int64) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateAccountID() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *ReconciliationAccountRuleUpsertOne) SetProvider(v string) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateProvider() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateProvider()
	})
}

// SetExternalKey sets the "external_key" field.
func (u *ReconciliationAccountRuleUpsertOne) SetExternalKey(v string) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetExternalKey(v)
	})
}

// UpdateExternalKey sets the "external_key" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateExternalKey() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateExternalKey()
	})
}

// SetMultiplier sets the "multiplier" field.
func (u *ReconciliationAccountRuleUpsertOne) SetMultiplier(v float64) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetMultiplier(v)
	})
}

// AddMultiplier adds v to the "multiplier" field.
func (u *ReconciliationAccountRuleUpsertOne) AddMultiplier(v float64) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.AddMultiplier(v)
	})
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateMultiplier() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateMultiplier()
	})
}

// ClearMultiplier clears the value of the "multiplier" field.
func (u *ReconciliationAccountRuleUpsertOne) ClearMultiplier() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.ClearMultiplier()
	})
}

// SetVersion sets the "version" field.
func (u *ReconciliationAccountRuleUpsertOne) SetVersion(v int64) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ReconciliationAccountRuleUpsertOne) AddVersion(v int64) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateVersion() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ReconciliationAccountRuleUpsertOne) SetEnabled(v bool) *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertOne) UpdateEnabled() *ReconciliationAccountRuleUpsertOne {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *ReconciliationAccountRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReconciliationAccountRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReconciliationAccountRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReconciliationAccountRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReconciliationAccountRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReconciliationAccountRuleCreateBulk is the builder for creating many ReconciliationAccountRule entities in bulk.
type ReconciliationAccountRuleCreateBulk struct {
	config
	err      error
	builders []*ReconciliationAccountRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the ReconciliationAccountRule entities in the database.
func (_c *ReconciliationAccountRuleCreateBulk) Save(ctx context.Context) ([]*ReconciliationAccountRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReconciliationAccountRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReconciliationAccountRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReconciliationAccountRuleCreateBulk) SaveX(ctx context.Context) []*ReconciliationAccountRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationAccountRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationAccountRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReconciliationAccountRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReconciliationAccountRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReconciliationAccountRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReconciliationAccountRuleUpsertBulk {
	_c.conflict = opts
	return &ReconciliationAccountRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReconciliationAccountRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReconciliationAccountRuleCreateBulk) OnConflictColumns(columns ...string) *ReconciliationAccountRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReconciliationAccountRuleUpsertBulk{
		create: _c,
	}
}

// ReconciliationAccountRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of ReconciliationAccountRule nodes.
type ReconciliationAccountRuleUpsertBulk struct {
	create *ReconciliationAccountRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReconciliationAccountRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReconciliationAccountRuleUpsertBulk) UpdateNewValues() *ReconciliationAccountRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(reconciliationaccountrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReconciliationAccountRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReconciliationAccountRuleUpsertBulk) Ignore() *ReconciliationAccountRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReconciliationAccountRuleUpsertBulk) DoNothing() *ReconciliationAccountRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReconciliationAccountRuleCreateBulk.OnConflict
// documentation for more info.
func (u *ReconciliationAccountRuleUpsertBulk) Update(set func(*ReconciliationAccountRuleUpsert)) *ReconciliationAccountRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReconciliationAccountRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetUpdatedAt(v time.Time) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateUpdatedAt() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetAccountID(v int64) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ReconciliationAccountRuleUpsertBulk) AddAccountID(v int64) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateAccountID() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetProvider(v string) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateProvider() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateProvider()
	})
}

// SetExternalKey sets the "external_key" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetExternalKey(v string) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetExternalKey(v)
	})
}

// UpdateExternalKey sets the "external_key" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateExternalKey() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateExternalKey()
	})
}

// SetMultiplier sets the "multiplier" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetMultiplier(v float64) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetMultiplier(v)
	})
}

// AddMultiplier adds v to the "multiplier" field.
func (u *ReconciliationAccountRuleUpsertBulk) AddMultiplier(v float64) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.AddMultiplier(v)
	})
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateMultiplier() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateMultiplier()
	})
}

// ClearMultiplier clears the value of the "multiplier" field.
func (u *ReconciliationAccountRuleUpsertBulk) ClearMultiplier() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.ClearMultiplier()
	})
}

// SetVersion sets the "version" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetVersion(v int64) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ReconciliationAccountRuleUpsertBulk) AddVersion(v int64) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateVersion() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ReconciliationAccountRuleUpsertBulk) SetEnabled(v bool) *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ReconciliationAccountRuleUpsertBulk) UpdateEnabled() *ReconciliationAccountRuleUpsertBulk {
	return u.Update(func(s *ReconciliationAccountRuleUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *ReconciliationAccountRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReconciliationAccountRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReconciliationAccountRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReconciliationAccountRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
