// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationupstreambill"
)

// ReconciliationUpstreamBillUpdate is the builder for updating ReconciliationUpstreamBill entities.
type ReconciliationUpstreamBillUpdate struct {
	config
	hooks    []Hook
	mutation *ReconciliationUpstreamBillMutation
}

// Where appends a list predicates to the ReconciliationUpstreamBillUpdate builder.
func (_u *ReconciliationUpstreamBillUpdate) Where(ps ...predicate.ReconciliationUpstreamBill) *ReconciliationUpstreamBillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationUpstreamBillUpdate) SetUpdatedAt(v time.Time) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ReconciliationUpstreamBillUpdate) SetProvider(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableProvider(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *ReconciliationUpstreamBillUpdate) SetUpstreamRequestID(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableUpstreamRequestID(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *ReconciliationUpstreamBillUpdate) SetOccurredAt(v time.Time) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableOccurredAt(v *time.Time) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetBillingDate sets the "billing_date" field.
func (_u *ReconciliationUpstreamBillUpdate) SetBillingDate(v time.Time) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetBillingDate(v)
	return _u
}

// SetNillableBillingDate sets the "billing_date" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableBillingDate(v *time.Time) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetBillingDate(*v)
	}
	return _u
}

// ClearBillingDate clears the value of the "billing_date" field.
func (_u *ReconciliationUpstreamBillUpdate) ClearBillingDate() *ReconciliationUpstreamBillUpdate {
	_u.mutation.ClearBillingDate()
	return _u
}

// SetModel sets the "model" field.
func (_u *ReconciliationUpstreamBillUpdate) SetModel(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableModel(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTokenName sets the "token_name" field.
func (_u *ReconciliationUpstreamBillUpdate) SetTokenName(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetTokenName(v)
	return _u
}

// SetNillableTokenName sets the "token_name" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableTokenName(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetTokenName(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) SetInputTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableInputTokens(v *int) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) AddInputTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) SetOutputTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableOutputTokens(v *int) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) AddOutputTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) SetCacheReadTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableCacheReadTokens(v *int) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) AddCacheReadTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) SetCacheCreationTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableCacheCreationTokens(v *int) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *ReconciliationUpstreamBillUpdate) AddCacheCreationTokens(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheTokensTotal sets the "cache_tokens_total" field.
func (_u *ReconciliationUpstreamBillUpdate) SetCacheTokensTotal(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetCacheTokensTotal()
	_u.mutation.SetCacheTokensTotal(v)
	return _u
}

// SetNillableCacheTokensTotal sets the "cache_tokens_total" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableCacheTokensTotal(v *int) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetCacheTokensTotal(*v)
	}
	return _u
}

// AddCacheTokensTotal adds value to the "cache_tokens_total" field.
func (_u *ReconciliationUpstreamBillUpdate) AddCacheTokensTotal(v int) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddCacheTokensTotal(v)
	return _u
}

// SetCostOriginal sets the "cost_original" field.
func (_u *ReconciliationUpstreamBillUpdate) SetCostOriginal(v float64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetCostOriginal()
	_u.mutation.SetCostOriginal(v)
	return _u
}

// SetNillableCostOriginal sets the "cost_original" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableCostOriginal(v *float64) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetCostOriginal(*v)
	}
	return _u
}

// AddCostOriginal adds value to the "cost_original" field.
func (_u *ReconciliationUpstreamBillUpdate) AddCostOriginal(v float64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddCostOriginal(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ReconciliationUpstreamBillUpdate) SetCurrency(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableCurrency(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (_u *ReconciliationUpstreamBillUpdate) SetFxRateToCny(v float64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetFxRateToCny()
	_u.mutation.SetFxRateToCny(v)
	return _u
}

// SetNillableFxRateToCny sets the "fx_rate_to_cny" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableFxRateToCny(v *float64) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetFxRateToCny(*v)
	}
	return _u
}

// AddFxRateToCny adds value to the "fx_rate_to_cny" field.
func (_u *ReconciliationUpstreamBillUpdate) AddFxRateToCny(v float64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddFxRateToCny(v)
	return _u
}

// SetCostCny sets the "cost_cny" field.
func (_u *ReconciliationUpstreamBillUpdate) SetCostCny(v float64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetCostCny()
	_u.mutation.SetCostCny(v)
	return _u
}

// SetNillableCostCny sets the "cost_cny" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableCostCny(v *float64) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetCostCny(*v)
	}
	return _u
}

// AddCostCny adds value to the "cost_cny" field.
func (_u *ReconciliationUpstreamBillUpdate) AddCostCny(v float64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddCostCny(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ReconciliationUpstreamBillUpdate) SetSource(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableSource(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetMatchState sets the "match_state" field.
func (_u *ReconciliationUpstreamBillUpdate) SetMatchState(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetMatchState(v)
	return _u
}

// SetNillableMatchState sets the "match_state" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableMatchState(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetMatchState(*v)
	}
	return _u
}

// SetMatchMethod sets the "match_method" field.
func (_u *ReconciliationUpstreamBillUpdate) SetMatchMethod(v string) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetMatchMethod(v)
	return _u
}

// SetNillableMatchMethod sets the "match_method" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableMatchMethod(v *string) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetMatchMethod(*v)
	}
	return _u
}

// SetMatchedUsageLogID sets the "matched_usage_log_id" field.
func (_u *ReconciliationUpstreamBillUpdate) SetMatchedUsageLogID(v int64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetMatchedUsageLogID()
	_u.mutation.SetMatchedUsageLogID(v)
	return _u
}

// SetNillableMatchedUsageLogID sets the "matched_usage_log_id" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableMatchedUsageLogID(v *int64) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetMatchedUsageLogID(*v)
	}
	return _u
}

// AddMatchedUsageLogID adds value to the "matched_usage_log_id" field.
func (_u *ReconciliationUpstreamBillUpdate) AddMatchedUsageLogID(v int64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddMatchedUsageLogID(v)
	return _u
}

// ClearMatchedUsageLogID clears the value of the "matched_usage_log_id" field.
func (_u *ReconciliationUpstreamBillUpdate) ClearMatchedUsageLogID() *ReconciliationUpstreamBillUpdate {
	_u.mutation.ClearMatchedUsageLogID()
	return _u
}

// SetMatchedAccountID sets the "matched_account_id" field.
func (_u *ReconciliationUpstreamBillUpdate) SetMatchedAccountID(v int64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.ResetMatchedAccountID()
	_u.mutation.SetMatchedAccountID(v)
	return _u
}

// SetNillableMatchedAccountID sets the "matched_account_id" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableMatchedAccountID(v *int64) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetMatchedAccountID(*v)
	}
	return _u
}

// AddMatchedAccountID adds value to the "matched_account_id" field.
func (_u *ReconciliationUpstreamBillUpdate) AddMatchedAccountID(v int64) *ReconciliationUpstreamBillUpdate {
	_u.mutation.AddMatchedAccountID(v)
	return _u
}

// ClearMatchedAccountID clears the value of the "matched_account_id" field.
func (_u *ReconciliationUpstreamBillUpdate) ClearMatchedAccountID() *ReconciliationUpstreamBillUpdate {
	_u.mutation.ClearMatchedAccountID()
	return _u
}

// SetRaw sets the "raw" field.
func (_u *ReconciliationUpstreamBillUpdate) SetRaw(v map[string]interface{}) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetRaw(v)
	return _u
}

// ClearRaw clears the value of the "raw" field.
func (_u *ReconciliationUpstreamBillUpdate) ClearRaw() *ReconciliationUpstreamBillUpdate {
	_u.mutation.ClearRaw()
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *ReconciliationUpstreamBillUpdate) SetImportedAt(v time.Time) *ReconciliationUpstreamBillUpdate {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdate) SetNillableImportedAt(v *time.Time) *ReconciliationUpstreamBillUpdate {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// Mutation returns the ReconciliationUpstreamBillMutation object of the builder.
func (_u *ReconciliationUpstreamBillUpdate) Mutation() *ReconciliationUpstreamBillMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReconciliationUpstreamBillUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationUpstreamBillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReconciliationUpstreamBillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationUpstreamBillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationUpstreamBillUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationupstreambill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationUpstreamBillUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := reconciliationupstreambill.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := reconciliationupstreambill.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := reconciliationupstreambill.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenName(); ok {
		if err := reconciliationupstreambill.TokenNameValidator(v); err != nil {
			return &ValidationError{Name: "token_name", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.token_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := reconciliationupstreambill.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := reconciliationupstreambill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchState(); ok {
		if err := reconciliationupstreambill.MatchStateValidator(v); err != nil {
			return &ValidationError{Name: "match_state", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.match_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMethod(); ok {
		if err := reconciliationupstreambill.MatchMethodValidator(v); err != nil {
			return &ValidationError{Name: "match_method", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.match_method": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationUpstreamBillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationupstreambill.Table, reconciliationupstreambill.Columns, sqlgraph.NewFieldSpec(reconciliationupstreambill.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationupstreambill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(reconciliationupstreambill.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(reconciliationupstreambill.FieldUpstreamRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(reconciliationupstreambill.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BillingDate(); ok {
		_spec.SetField(reconciliationupstreambill.FieldBillingDate, field.TypeTime, value)
	}
	if _u.mutation.BillingDateCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldBillingDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(reconciliationupstreambill.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenName(); ok {
		_spec.SetField(reconciliationupstreambill.FieldTokenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCacheReadTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCacheReadTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCacheCreationTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCacheCreationTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheTokensTotal(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCacheTokensTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheTokensTotal(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCacheTokensTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostOriginal(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCostOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostOriginal(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCostOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.FxRateToCny(); ok {
		_spec.SetField(reconciliationupstreambill.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFxRateToCny(); ok {
		_spec.AddField(reconciliationupstreambill.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostCny(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostCny(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(reconciliationupstreambill.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchState(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchState, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchMethod(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedUsageLogID(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchedUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMatchedUsageLogID(); ok {
		_spec.AddField(reconciliationupstreambill.FieldMatchedUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.MatchedUsageLogIDCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldMatchedUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.MatchedAccountID(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMatchedAccountID(); ok {
		_spec.AddField(reconciliationupstreambill.FieldMatchedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.MatchedAccountIDCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldMatchedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(reconciliationupstreambill.FieldRaw, field.TypeJSON, value)
	}
	if _u.mutation.RawCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldRaw, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(reconciliationupstreambill.FieldImportedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationupstreambill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReconciliationUpstreamBillUpdateOne is the builder for updating a single ReconciliationUpstreamBill entity.
type ReconciliationUpstreamBillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReconciliationUpstreamBillMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetUpdatedAt(v time.Time) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetProvider(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableProvider(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetUpstreamRequestID(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableUpstreamRequestID(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetOccurredAt(v time.Time) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableOccurredAt(v *time.Time) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetBillingDate sets the "billing_date" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetBillingDate(v time.Time) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetBillingDate(v)
	return _u
}

// SetNillableBillingDate sets the "billing_date" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableBillingDate(v *time.Time) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetBillingDate(*v)
	}
	return _u
}

// ClearBillingDate clears the value of the "billing_date" field.
func (_u *ReconciliationUpstreamBillUpdateOne) ClearBillingDate() *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ClearBillingDate()
	return _u
}

// SetModel sets the "model" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetModel(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableModel(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTokenName sets the "token_name" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetTokenName(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetTokenName(v)
	return _u
}

// SetNillableTokenName sets the "token_name" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableTokenName(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetTokenName(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetInputTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableInputTokens(v *int) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddInputTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetOutputTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableOutputTokens(v *int) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddOutputTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetCacheReadTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableCacheReadTokens(v *int) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddCacheReadTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetCacheCreationTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableCacheCreationTokens(v *int) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddCacheCreationTokens(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheTokensTotal sets the "cache_tokens_total" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetCacheTokensTotal(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetCacheTokensTotal()
	_u.mutation.SetCacheTokensTotal(v)
	return _u
}

// SetNillableCacheTokensTotal sets the "cache_tokens_total" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableCacheTokensTotal(v *int) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetCacheTokensTotal(*v)
	}
	return _u
}

// AddCacheTokensTotal adds value to the "cache_tokens_total" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddCacheTokensTotal(v int) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddCacheTokensTotal(v)
	return _u
}

// SetCostOriginal sets the "cost_original" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetCostOriginal(v float64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetCostOriginal()
	_u.mutation.SetCostOriginal(v)
	return _u
}

// SetNillableCostOriginal sets the "cost_original" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableCostOriginal(v *float64) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetCostOriginal(*v)
	}
	return _u
}

// AddCostOriginal adds value to the "cost_original" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddCostOriginal(v float64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddCostOriginal(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetCurrency(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableCurrency(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetFxRateToCny(v float64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetFxRateToCny()
	_u.mutation.SetFxRateToCny(v)
	return _u
}

// SetNillableFxRateToCny sets the "fx_rate_to_cny" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableFxRateToCny(v *float64) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetFxRateToCny(*v)
	}
	return _u
}

// AddFxRateToCny adds value to the "fx_rate_to_cny" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddFxRateToCny(v float64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddFxRateToCny(v)
	return _u
}

// SetCostCny sets the "cost_cny" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetCostCny(v float64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetCostCny()
	_u.mutation.SetCostCny(v)
	return _u
}

// SetNillableCostCny sets the "cost_cny" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableCostCny(v *float64) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetCostCny(*v)
	}
	return _u
}

// AddCostCny adds value to the "cost_cny" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddCostCny(v float64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddCostCny(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetSource(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableSource(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetMatchState sets the "match_state" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetMatchState(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetMatchState(v)
	return _u
}

// SetNillableMatchState sets the "match_state" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableMatchState(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetMatchState(*v)
	}
	return _u
}

// SetMatchMethod sets the "match_method" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetMatchMethod(v string) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetMatchMethod(v)
	return _u
}

// SetNillableMatchMethod sets the "match_method" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableMatchMethod(v *string) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetMatchMethod(*v)
	}
	return _u
}

// SetMatchedUsageLogID sets the "matched_usage_log_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetMatchedUsageLogID(v int64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetMatchedUsageLogID()
	_u.mutation.SetMatchedUsageLogID(v)
	return _u
}

// SetNillableMatchedUsageLogID sets the "matched_usage_log_id" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableMatchedUsageLogID(v *int64) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetMatchedUsageLogID(*v)
	}
	return _u
}

// AddMatchedUsageLogID adds value to the "matched_usage_log_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddMatchedUsageLogID(v int64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddMatchedUsageLogID(v)
	return _u
}

// ClearMatchedUsageLogID clears the value of the "matched_usage_log_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) ClearMatchedUsageLogID() *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ClearMatchedUsageLogID()
	return _u
}

// SetMatchedAccountID sets the "matched_account_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetMatchedAccountID(v int64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ResetMatchedAccountID()
	_u.mutation.SetMatchedAccountID(v)
	return _u
}

// SetNillableMatchedAccountID sets the "matched_account_id" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableMatchedAccountID(v *int64) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetMatchedAccountID(*v)
	}
	return _u
}

// AddMatchedAccountID adds value to the "matched_account_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) AddMatchedAccountID(v int64) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.AddMatchedAccountID(v)
	return _u
}

// ClearMatchedAccountID clears the value of the "matched_account_id" field.
func (_u *ReconciliationUpstreamBillUpdateOne) ClearMatchedAccountID() *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ClearMatchedAccountID()
	return _u
}

// SetRaw sets the "raw" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetRaw(v map[string]interface{}) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetRaw(v)
	return _u
}

// ClearRaw clears the value of the "raw" field.
func (_u *ReconciliationUpstreamBillUpdateOne) ClearRaw() *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.ClearRaw()
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *ReconciliationUpstreamBillUpdateOne) SetImportedAt(v time.Time) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *ReconciliationUpstreamBillUpdateOne) SetNillableImportedAt(v *time.Time) *ReconciliationUpstreamBillUpdateOne {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// Mutation returns the ReconciliationUpstreamBillMutation object of the builder.
func (_u *ReconciliationUpstreamBillUpdateOne) Mutation() *ReconciliationUpstreamBillMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReconciliationUpstreamBillUpdate builder.
func (_u *ReconciliationUpstreamBillUpdateOne) Where(ps ...predicate.ReconciliationUpstreamBill) *ReconciliationUpstreamBillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReconciliationUpstreamBillUpdateOne) Select(field string, fields ...string) *ReconciliationUpstreamBillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReconciliationUpstreamBill entity.
func (_u *ReconciliationUpstreamBillUpdateOne) Save(ctx context.Context) (*ReconciliationUpstreamBill, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationUpstreamBillUpdateOne) SaveX(ctx context.Context) *ReconciliationUpstreamBill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReconciliationUpstreamBillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationUpstreamBillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationUpstreamBillUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationupstreambill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationUpstreamBillUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := reconciliationupstreambill.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := reconciliationupstreambill.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := reconciliationupstreambill.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenName(); ok {
		if err := reconciliationupstreambill.TokenNameValidator(v); err != nil {
			return &ValidationError{Name: "token_name", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.token_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := reconciliationupstreambill.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := reconciliationupstreambill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchState(); ok {
		if err := reconciliationupstreambill.MatchStateValidator(v); err != nil {
			return &ValidationError{Name: "match_state", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.match_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMethod(); ok {
		if err := reconciliationupstreambill.MatchMethodValidator(v); err != nil {
			return &ValidationError{Name: "match_method", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUpstreamBill.match_method": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationUpstreamBillUpdateOne) sqlSave(ctx context.Context) (_node *ReconciliationUpstreamBill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationupstreambill.Table, reconciliationupstreambill.Columns, sqlgraph.NewFieldSpec(reconciliationupstreambill.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReconciliationUpstreamBill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reconciliationupstreambill.FieldID)
		for _, f := range fields {
			if !reconciliationupstreambill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reconciliationupstreambill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationupstreambill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(reconciliationupstreambill.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(reconciliationupstreambill.FieldUpstreamRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(reconciliationupstreambill.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BillingDate(); ok {
		_spec.SetField(reconciliationupstreambill.FieldBillingDate, field.TypeTime, value)
	}
	if _u.mutation.BillingDateCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldBillingDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(reconciliationupstreambill.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenName(); ok {
		_spec.SetField(reconciliationupstreambill.FieldTokenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCacheReadTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCacheReadTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCacheCreationTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCacheCreationTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheTokensTotal(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCacheTokensTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheTokensTotal(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCacheTokensTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostOriginal(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCostOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostOriginal(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCostOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.FxRateToCny(); ok {
		_spec.SetField(reconciliationupstreambill.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFxRateToCny(); ok {
		_spec.AddField(reconciliationupstreambill.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostCny(); ok {
		_spec.SetField(reconciliationupstreambill.FieldCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostCny(); ok {
		_spec.AddField(reconciliationupstreambill.FieldCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(reconciliationupstreambill.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchState(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchState, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchMethod(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedUsageLogID(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchedUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMatchedUsageLogID(); ok {
		_spec.AddField(reconciliationupstreambill.FieldMatchedUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.MatchedUsageLogIDCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldMatchedUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.MatchedAccountID(); ok {
		_spec.SetField(reconciliationupstreambill.FieldMatchedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMatchedAccountID(); ok {
		_spec.AddField(reconciliationupstreambill.FieldMatchedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.MatchedAccountIDCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldMatchedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(reconciliationupstreambill.FieldRaw, field.TypeJSON, value)
	}
	if _u.mutation.RawCleared() {
		_spec.ClearField(reconciliationupstreambill.FieldRaw, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(reconciliationupstreambill.FieldImportedAt, field.TypeTime, value)
	}
	_node = &ReconciliationUpstreamBill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationupstreambill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
