// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationupstreambill"
)

// ReconciliationUpstreamBill is the model entity for the ReconciliationUpstreamBill schema.
type ReconciliationUpstreamBill struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 上游提供方，目前恒为 a6
	Provider string `json:"provider,omitempty"`
	// 上游账单声明的请求标识，用于直连匹配
	UpstreamRequestID string `json:"upstream_request_id,omitempty"`
	// 上游账单发生时间
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// 上游账单归属日期，便于按日核对
	BillingDate *time.Time `json:"billing_date,omitempty"`
	// 上游记录的模型名
	Model string `json:"model,omitempty"`
	// 上游令牌名，用于关联本站账号
	TokenName string `json:"token_name,omitempty"`
	// 输入 token 数，组合匹配依据
	InputTokens int `json:"input_tokens,omitempty"`
	// 输出 token 数，组合匹配依据
	OutputTokens int `json:"output_tokens,omitempty"`
	// 缓存读取 token 数，组合匹配依据
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// 缓存写入 token 数，组合匹配依据
	CacheCreationTokens int `json:"cache_creation_tokens,omitempty"`
	// 上游口径的缓存合计；上游只回合并值时分列为 0，组合匹配以本列为准
	CacheTokensTotal int `json:"cache_tokens_total,omitempty"`
	// 上游原币金额
	CostOriginal float64 `json:"cost_original,omitempty"`
	// 上游结算币种
	Currency string `json:"currency,omitempty"`
	// 导入时的美元->人民币换算数字快照
	FxRateToCny float64 `json:"fx_rate_to_cny,omitempty"`
	// 换算后的上游成本，落库即冻结
	CostCny float64 `json:"cost_cny,omitempty"`
	// 账单来源：a6 自动同步 / manual_import 人工导入
	Source string `json:"source,omitempty"`
	// 匹配状态：staging / matched / unmatched
	MatchState string `json:"match_state,omitempty"`
	// 匹配方式，记录是四级匹配中的哪一级命中的
	MatchMethod string `json:"match_method,omitempty"`
	// 匹配到的本站调用 ID（usage_logs.id）
	MatchedUsageLogID *int64 `json:"matched_usage_log_id,omitempty"`
	// 匹配到的本站账号 ID
	MatchedAccountID *int64 `json:"matched_account_id,omitempty"`
	// 上游原始账单留存，便于追溯与重放
	Raw map[string]interface{} `json:"raw,omitempty"`
	// 导入时间
	ImportedAt   time.Time `json:"imported_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReconciliationUpstreamBill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reconciliationupstreambill.FieldRaw:
			values[i] = new([]byte)
		case reconciliationupstreambill.FieldCostOriginal, reconciliationupstreambill.FieldFxRateToCny, reconciliationupstreambill.FieldCostCny:
			values[i] = new(sql.NullFloat64)
		case reconciliationupstreambill.FieldID, reconciliationupstreambill.FieldInputTokens, reconciliationupstreambill.FieldOutputTokens, reconciliationupstreambill.FieldCacheReadTokens, reconciliationupstreambill.FieldCacheCreationTokens, reconciliationupstreambill.FieldCacheTokensTotal, reconciliationupstreambill.FieldMatchedUsageLogID, reconciliationupstreambill.FieldMatchedAccountID:
			values[i] = new(sql.NullInt64)
		case reconciliationupstreambill.FieldProvider, reconciliationupstreambill.FieldUpstreamRequestID, reconciliationupstreambill.FieldModel, reconciliationupstreambill.FieldTokenName, reconciliationupstreambill.FieldCurrency, reconciliationupstreambill.FieldSource, reconciliationupstreambill.FieldMatchState, reconciliationupstreambill.FieldMatchMethod:
			values[i] = new(sql.NullString)
		case reconciliationupstreambill.FieldCreatedAt, reconciliationupstreambill.FieldUpdatedAt, reconciliationupstreambill.FieldOccurredAt, reconciliationupstreambill.FieldBillingDate, reconciliationupstreambill.FieldImportedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReconciliationUpstreamBill fields.
func (_m *ReconciliationUpstreamBill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reconciliationupstreambill.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case reconciliationupstreambill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reconciliationupstreambill.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case reconciliationupstreambill.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case reconciliationupstreambill.FieldUpstreamRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamRequestID = value.String
			}
		case reconciliationupstreambill.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case reconciliationupstreambill.FieldBillingDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field billing_date", values[i])
			} else if value.Valid {
				_m.BillingDate = new(time.Time)
				*_m.BillingDate = value.Time
			}
		case reconciliationupstreambill.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case reconciliationupstreambill.FieldTokenName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_name", values[i])
			} else if value.Valid {
				_m.TokenName = value.String
			}
		case reconciliationupstreambill.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case reconciliationupstreambill.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case reconciliationupstreambill.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = int(value.Int64)
			}
		case reconciliationupstreambill.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = int(value.Int64)
			}
		case reconciliationupstreambill.FieldCacheTokensTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_tokens_total", values[i])
			} else if value.Valid {
				_m.CacheTokensTotal = int(value.Int64)
			}
		case reconciliationupstreambill.FieldCostOriginal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_original", values[i])
			} else if value.Valid {
				_m.CostOriginal = value.Float64
			}
		case reconciliationupstreambill.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case reconciliationupstreambill.FieldFxRateToCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fx_rate_to_cny", values[i])
			} else if value.Valid {
				_m.FxRateToCny = value.Float64
			}
		case reconciliationupstreambill.FieldCostCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_cny", values[i])
			} else if value.Valid {
				_m.CostCny = value.Float64
			}
		case reconciliationupstreambill.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case reconciliationupstreambill.FieldMatchState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_state", values[i])
			} else if value.Valid {
				_m.MatchState = value.String
			}
		case reconciliationupstreambill.FieldMatchMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_method", values[i])
			} else if value.Valid {
				_m.MatchMethod = value.String
			}
		case reconciliationupstreambill.FieldMatchedUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field matched_usage_log_id", values[i])
			} else if value.Valid {
				_m.MatchedUsageLogID = new(int64)
				*_m.MatchedUsageLogID = value.Int64
			}
		case reconciliationupstreambill.FieldMatchedAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field matched_account_id", values[i])
			} else if value.Valid {
				_m.MatchedAccountID = new(int64)
				*_m.MatchedAccountID = value.Int64
			}
		case reconciliationupstreambill.FieldRaw:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Raw); err != nil {
					return fmt.Errorf("unmarshal field raw: %w", err)
				}
			}
		case reconciliationupstreambill.FieldImportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field imported_at", values[i])
			} else if value.Valid {
				_m.ImportedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReconciliationUpstreamBill.
// This includes values selected through modifiers, order, etc.
func (_m *ReconciliationUpstreamBill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReconciliationUpstreamBill.
// Note that you need to call ReconciliationUpstreamBill.Unwrap() before calling this method if this ReconciliationUpstreamBill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReconciliationUpstreamBill) Update() *ReconciliationUpstreamBillUpdateOne {
	return NewReconciliationUpstreamBillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReconciliationUpstreamBill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReconciliationUpstreamBill) Unwrap() *ReconciliationUpstreamBill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReconciliationUpstreamBill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReconciliationUpstreamBill) String() string {
	var builder strings.Builder
	builder.WriteString("ReconciliationUpstreamBill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("upstream_request_id=")
	builder.WriteString(_m.UpstreamRequestID)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.BillingDate; v != nil {
		builder.WriteString("billing_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("token_name=")
	builder.WriteString(_m.TokenName)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_tokens_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheTokensTotal))
	builder.WriteString(", ")
	builder.WriteString("cost_original=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostOriginal))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("fx_rate_to_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.FxRateToCny))
	builder.WriteString(", ")
	builder.WriteString("cost_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostCny))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("match_state=")
	builder.WriteString(_m.MatchState)
	builder.WriteString(", ")
	builder.WriteString("match_method=")
	builder.WriteString(_m.MatchMethod)
	builder.WriteString(", ")
	if v := _m.MatchedUsageLogID; v != nil {
		builder.WriteString("matched_usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MatchedAccountID; v != nil {
		builder.WriteString("matched_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("raw=")
	builder.WriteString(fmt.Sprintf("%v", _m.Raw))
	builder.WriteString(", ")
	builder.WriteString("imported_at=")
	builder.WriteString(_m.ImportedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReconciliationUpstreamBills is a parsable slice of ReconciliationUpstreamBill.
type ReconciliationUpstreamBills []*ReconciliationUpstreamBill
