// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationsyncstate"
)

// ReconciliationSyncStateUpdate is the builder for updating ReconciliationSyncState entities.
type ReconciliationSyncStateUpdate struct {
	config
	hooks    []Hook
	mutation *ReconciliationSyncStateMutation
}

// Where appends a list predicates to the ReconciliationSyncStateUpdate builder.
func (_u *ReconciliationSyncStateUpdate) Where(ps ...predicate.ReconciliationSyncState) *ReconciliationSyncStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *ReconciliationSyncStateUpdate) SetKey(v string) *ReconciliationSyncStateUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ReconciliationSyncStateUpdate) SetNillableKey(v *string) *ReconciliationSyncStateUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ReconciliationSyncStateUpdate) SetValue(v string) *ReconciliationSyncStateUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ReconciliationSyncStateUpdate) SetNillableValue(v *string) *ReconciliationSyncStateUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationSyncStateUpdate) SetUpdatedAt(v time.Time) *ReconciliationSyncStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReconciliationSyncStateMutation object of the builder.
func (_u *ReconciliationSyncStateUpdate) Mutation() *ReconciliationSyncStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReconciliationSyncStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationSyncStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReconciliationSyncStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationSyncStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationSyncStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationsyncstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationSyncStateUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := reconciliationsyncstate.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationSyncState.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationSyncStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationsyncstate.Table, reconciliationsyncstate.Columns, sqlgraph.NewFieldSpec(reconciliationsyncstate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(reconciliationsyncstate.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(reconciliationsyncstate.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationsyncstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationsyncstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReconciliationSyncStateUpdateOne is the builder for updating a single ReconciliationSyncState entity.
type ReconciliationSyncStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReconciliationSyncStateMutation
}

// SetKey sets the "key" field.
func (_u *ReconciliationSyncStateUpdateOne) SetKey(v string) *ReconciliationSyncStateUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ReconciliationSyncStateUpdateOne) SetNillableKey(v *string) *ReconciliationSyncStateUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ReconciliationSyncStateUpdateOne) SetValue(v string) *ReconciliationSyncStateUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ReconciliationSyncStateUpdateOne) SetNillableValue(v *string) *ReconciliationSyncStateUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationSyncStateUpdateOne) SetUpdatedAt(v time.Time) *ReconciliationSyncStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReconciliationSyncStateMutation object of the builder.
func (_u *ReconciliationSyncStateUpdateOne) Mutation() *ReconciliationSyncStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReconciliationSyncStateUpdate builder.
func (_u *ReconciliationSyncStateUpdateOne) Where(ps ...predicate.ReconciliationSyncState) *ReconciliationSyncStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReconciliationSyncStateUpdateOne) Select(field string, fields ...string) *ReconciliationSyncStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReconciliationSyncState entity.
func (_u *ReconciliationSyncStateUpdateOne) Save(ctx context.Context) (*ReconciliationSyncState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationSyncStateUpdateOne) SaveX(ctx context.Context) *ReconciliationSyncState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReconciliationSyncStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationSyncStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationSyncStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationsyncstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationSyncStateUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := reconciliationsyncstate.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationSyncState.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationSyncStateUpdateOne) sqlSave(ctx context.Context) (_node *ReconciliationSyncState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationsyncstate.Table, reconciliationsyncstate.Columns, sqlgraph.NewFieldSpec(reconciliationsyncstate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReconciliationSyncState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reconciliationsyncstate.FieldID)
		for _, f := range fields {
			if !reconciliationsyncstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reconciliationsyncstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(reconciliationsyncstate.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(reconciliationsyncstate.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationsyncstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ReconciliationSyncState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationsyncstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
