// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationusageextra"
)

// ReconciliationUsageExtraCreate is the builder for creating a ReconciliationUsageExtra entity.
type ReconciliationUsageExtraCreate struct {
	config
	mutation *ReconciliationUsageExtraMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReconciliationUsageExtraCreate) SetCreatedAt(v time.Time) *ReconciliationUsageExtraCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableCreatedAt(v *time.Time) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReconciliationUsageExtraCreate) SetUpdatedAt(v time.Time) *ReconciliationUsageExtraCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableUpdatedAt(v *time.Time) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *ReconciliationUsageExtraCreate) SetUsageLogID(v int64) *ReconciliationUsageExtraCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ReconciliationUsageExtraCreate) SetAccountID(v int64) *ReconciliationUsageExtraCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetRuleProvider sets the "rule_provider" field.
func (_c *ReconciliationUsageExtraCreate) SetRuleProvider(v string) *ReconciliationUsageExtraCreate {
	_c.mutation.SetRuleProvider(v)
	return _c
}

// SetNillableRuleProvider sets the "rule_provider" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableRuleProvider(v *string) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetRuleProvider(*v)
	}
	return _c
}

// SetRuleExternalKey sets the "rule_external_key" field.
func (_c *ReconciliationUsageExtraCreate) SetRuleExternalKey(v string) *ReconciliationUsageExtraCreate {
	_c.mutation.SetRuleExternalKey(v)
	return _c
}

// SetNillableRuleExternalKey sets the "rule_external_key" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableRuleExternalKey(v *string) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetRuleExternalKey(*v)
	}
	return _c
}

// SetRuleVersion sets the "rule_version" field.
func (_c *ReconciliationUsageExtraCreate) SetRuleVersion(v int64) *ReconciliationUsageExtraCreate {
	_c.mutation.SetRuleVersion(v)
	return _c
}

// SetNillableRuleVersion sets the "rule_version" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableRuleVersion(v *int64) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetRuleVersion(*v)
	}
	return _c
}

// SetRevenueOriginal sets the "revenue_original" field.
func (_c *ReconciliationUsageExtraCreate) SetRevenueOriginal(v float64) *ReconciliationUsageExtraCreate {
	_c.mutation.SetRevenueOriginal(v)
	return _c
}

// SetNillableRevenueOriginal sets the "revenue_original" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableRevenueOriginal(v *float64) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetRevenueOriginal(*v)
	}
	return _c
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (_c *ReconciliationUsageExtraCreate) SetFxRateToCny(v float64) *ReconciliationUsageExtraCreate {
	_c.mutation.SetFxRateToCny(v)
	return _c
}

// SetNillableFxRateToCny sets the "fx_rate_to_cny" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableFxRateToCny(v *float64) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetFxRateToCny(*v)
	}
	return _c
}

// SetRevenueCny sets the "revenue_cny" field.
func (_c *ReconciliationUsageExtraCreate) SetRevenueCny(v float64) *ReconciliationUsageExtraCreate {
	_c.mutation.SetRevenueCny(v)
	return _c
}

// SetNillableRevenueCny sets the "revenue_cny" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableRevenueCny(v *float64) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetRevenueCny(*v)
	}
	return _c
}

// SetCollectedAt sets the "collected_at" field.
func (_c *ReconciliationUsageExtraCreate) SetCollectedAt(v time.Time) *ReconciliationUsageExtraCreate {
	_c.mutation.SetCollectedAt(v)
	return _c
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_c *ReconciliationUsageExtraCreate) SetNillableCollectedAt(v *time.Time) *ReconciliationUsageExtraCreate {
	if v != nil {
		_c.SetCollectedAt(*v)
	}
	return _c
}

// Mutation returns the ReconciliationUsageExtraMutation object of the builder.
func (_c *ReconciliationUsageExtraCreate) Mutation() *ReconciliationUsageExtraMutation {
	return _c.mutation
}

// Save creates the ReconciliationUsageExtra in the database.
func (_c *ReconciliationUsageExtraCreate) Save(ctx context.Context) (*ReconciliationUsageExtra, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReconciliationUsageExtraCreate) SaveX(ctx context.Context) *ReconciliationUsageExtra {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationUsageExtraCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationUsageExtraCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReconciliationUsageExtraCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reconciliationusageextra.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := reconciliationusageextra.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RuleProvider(); !ok {
		v := reconciliationusageextra.DefaultRuleProvider
		_c.mutation.SetRuleProvider(v)
	}
	if _, ok := _c.mutation.RuleExternalKey(); !ok {
		v := reconciliationusageextra.DefaultRuleExternalKey
		_c.mutation.SetRuleExternalKey(v)
	}
	if _, ok := _c.mutation.RuleVersion(); !ok {
		v := reconciliationusageextra.DefaultRuleVersion
		_c.mutation.SetRuleVersion(v)
	}
	if _, ok := _c.mutation.RevenueOriginal(); !ok {
		v := reconciliationusageextra.DefaultRevenueOriginal
		_c.mutation.SetRevenueOriginal(v)
	}
	if _, ok := _c.mutation.FxRateToCny(); !ok {
		v := reconciliationusageextra.DefaultFxRateToCny
		_c.mutation.SetFxRateToCny(v)
	}
	if _, ok := _c.mutation.RevenueCny(); !ok {
		v := reconciliationusageextra.DefaultRevenueCny
		_c.mutation.SetRevenueCny(v)
	}
	if _, ok := _c.mutation.CollectedAt(); !ok {
		v := reconciliationusageextra.DefaultCollectedAt()
		_c.mutation.SetCollectedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReconciliationUsageExtraCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.updated_at"`)}
	}
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.usage_log_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.account_id"`)}
	}
	if _, ok := _c.mutation.RuleProvider(); !ok {
		return &ValidationError{Name: "rule_provider", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.rule_provider"`)}
	}
	if v, ok := _c.mutation.RuleProvider(); ok {
		if err := reconciliationusageextra.RuleProviderValidator(v); err != nil {
			return &ValidationError{Name: "rule_provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUsageExtra.rule_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RuleExternalKey(); !ok {
		return &ValidationError{Name: "rule_external_key", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.rule_external_key"`)}
	}
	if v, ok := _c.mutation.RuleExternalKey(); ok {
		if err := reconciliationusageextra.RuleExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "rule_external_key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUsageExtra.rule_external_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RuleVersion(); !ok {
		return &ValidationError{Name: "rule_version", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.rule_version"`)}
	}
	if _, ok := _c.mutation.RevenueOriginal(); !ok {
		return &ValidationError{Name: "revenue_original", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.revenue_original"`)}
	}
	if _, ok := _c.mutation.FxRateToCny(); !ok {
		return &ValidationError{Name: "fx_rate_to_cny", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.fx_rate_to_cny"`)}
	}
	if _, ok := _c.mutation.RevenueCny(); !ok {
		return &ValidationError{Name: "revenue_cny", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.revenue_cny"`)}
	}
	if _, ok := _c.mutation.CollectedAt(); !ok {
		return &ValidationError{Name: "collected_at", err: errors.New(`ent: missing required field "ReconciliationUsageExtra.collected_at"`)}
	}
	return nil
}

func (_c *ReconciliationUsageExtraCreate) sqlSave(ctx context.Context) (*ReconciliationUsageExtra, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReconciliationUsageExtraCreate) createSpec() (*ReconciliationUsageExtra, *sqlgraph.CreateSpec) {
	var (
		_node = &ReconciliationUsageExtra{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reconciliationusageextra.Table, sqlgraph.NewFieldSpec(reconciliationusageextra.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(reconciliationusageextra.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(reconciliationusageextra.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.RuleProvider(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleProvider, field.TypeString, value)
		_node.RuleProvider = value
	}
	if value, ok := _c.mutation.RuleExternalKey(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleExternalKey, field.TypeString, value)
		_node.RuleExternalKey = value
	}
	if value, ok := _c.mutation.RuleVersion(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleVersion, field.TypeInt64, value)
		_node.RuleVersion = value
	}
	if value, ok := _c.mutation.RevenueOriginal(); ok {
		_spec.SetField(reconciliationusageextra.FieldRevenueOriginal, field.TypeFloat64, value)
		_node.RevenueOriginal = value
	}
	if value, ok := _c.mutation.FxRateToCny(); ok {
		_spec.SetField(reconciliationusageextra.FieldFxRateToCny, field.TypeFloat64, value)
		_node.FxRateToCny = value
	}
	if value, ok := _c.mutation.RevenueCny(); ok {
		_spec.SetField(reconciliationusageextra.FieldRevenueCny, field.TypeFloat64, value)
		_node.RevenueCny = value
	}
	if value, ok := _c.mutation.CollectedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldCollectedAt, field.TypeTime, value)
		_node.CollectedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReconciliationUsageExtra.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReconciliationUsageExtraUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReconciliationUsageExtraCreate) OnConflict(opts ...sql.ConflictOption) *ReconciliationUsageExtraUpsertOne {
	_c.conflict = opts
	return &ReconciliationUsageExtraUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReconciliationUsageExtra.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReconciliationUsageExtraCreate) OnConflictColumns(columns ...string) *ReconciliationUsageExtraUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReconciliationUsageExtraUpsertOne{
		create: _c,
	}
}

type (
	// ReconciliationUsageExtraUpsertOne is the builder for "upsert"-ing
	//  one ReconciliationUsageExtra node.
	ReconciliationUsageExtraUpsertOne struct {
		create *ReconciliationUsageExtraCreate
	}

	// ReconciliationUsageExtraUpsert is the "OnConflict" setter.
	ReconciliationUsageExtraUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationUsageExtraUpsert) SetUpdatedAt(v time.Time) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateUpdatedAt() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldUpdatedAt)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ReconciliationUsageExtraUpsert) SetUsageLogID(v int64) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateUsageLogID() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ReconciliationUsageExtraUpsert) AddUsageLogID(v int64) *ReconciliationUsageExtraUpsert {
	u.Add(reconciliationusageextra.FieldUsageLogID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ReconciliationUsageExtraUpsert) SetAccountID(v int64) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateAccountID() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ReconciliationUsageExtraUpsert) AddAccountID(v int64) *ReconciliationUsageExtraUpsert {
	u.Add(reconciliationusageextra.FieldAccountID, v)
	return u
}

// SetRuleProvider sets the "rule_provider" field.
func (u *ReconciliationUsageExtraUpsert) SetRuleProvider(v string) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldRuleProvider, v)
	return u
}

// UpdateRuleProvider sets the "rule_provider" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateRuleProvider() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldRuleProvider)
	return u
}

// SetRuleExternalKey sets the "rule_external_key" field.
func (u *ReconciliationUsageExtraUpsert) SetRuleExternalKey(v string) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldRuleExternalKey, v)
	return u
}

// UpdateRuleExternalKey sets the "rule_external_key" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateRuleExternalKey() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldRuleExternalKey)
	return u
}

// SetRuleVersion sets the "rule_version" field.
func (u *ReconciliationUsageExtraUpsert) SetRuleVersion(v int64) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldRuleVersion, v)
	return u
}

// UpdateRuleVersion sets the "rule_version" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateRuleVersion() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldRuleVersion)
	return u
}

// AddRuleVersion adds v to the "rule_version" field.
func (u *ReconciliationUsageExtraUpsert) AddRuleVersion(v int64) *ReconciliationUsageExtraUpsert {
	u.Add(reconciliationusageextra.FieldRuleVersion, v)
	return u
}

// SetRevenueOriginal sets the "revenue_original" field.
func (u *ReconciliationUsageExtraUpsert) SetRevenueOriginal(v float64) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldRevenueOriginal, v)
	return u
}

// UpdateRevenueOriginal sets the "revenue_original" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateRevenueOriginal() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldRevenueOriginal)
	return u
}

// AddRevenueOriginal adds v to the "revenue_original" field.
func (u *ReconciliationUsageExtraUpsert) AddRevenueOriginal(v float64) *ReconciliationUsageExtraUpsert {
	u.Add(reconciliationusageextra.FieldRevenueOriginal, v)
	return u
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (u *ReconciliationUsageExtraUpsert) SetFxRateToCny(v float64) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldFxRateToCny, v)
	return u
}

// UpdateFxRateToCny sets the "fx_rate_to_cny" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateFxRateToCny() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldFxRateToCny)
	return u
}

// AddFxRateToCny adds v to the "fx_rate_to_cny" field.
func (u *ReconciliationUsageExtraUpsert) AddFxRateToCny(v float64) *ReconciliationUsageExtraUpsert {
	u.Add(reconciliationusageextra.FieldFxRateToCny, v)
	return u
}

// SetRevenueCny sets the "revenue_cny" field.
func (u *ReconciliationUsageExtraUpsert) SetRevenueCny(v float64) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldRevenueCny, v)
	return u
}

// UpdateRevenueCny sets the "revenue_cny" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateRevenueCny() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldRevenueCny)
	return u
}

// AddRevenueCny adds v to the "revenue_cny" field.
func (u *ReconciliationUsageExtraUpsert) AddRevenueCny(v float64) *ReconciliationUsageExtraUpsert {
	u.Add(reconciliationusageextra.FieldRevenueCny, v)
	return u
}

// SetCollectedAt sets the "collected_at" field.
func (u *ReconciliationUsageExtraUpsert) SetCollectedAt(v time.Time) *ReconciliationUsageExtraUpsert {
	u.Set(reconciliationusageextra.FieldCollectedAt, v)
	return u
}

// UpdateCollectedAt sets the "collected_at" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsert) UpdateCollectedAt() *ReconciliationUsageExtraUpsert {
	u.SetExcluded(reconciliationusageextra.FieldCollectedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReconciliationUsageExtra.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReconciliationUsageExtraUpsertOne) UpdateNewValues() *ReconciliationUsageExtraUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(reconciliationusageextra.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReconciliationUsageExtra.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReconciliationUsageExtraUpsertOne) Ignore() *ReconciliationUsageExtraUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReconciliationUsageExtraUpsertOne) DoNothing() *ReconciliationUsageExtraUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReconciliationUsageExtraCreate.OnConflict
// documentation for more info.
func (u *ReconciliationUsageExtraUpsertOne) Update(set func(*ReconciliationUsageExtraUpsert)) *ReconciliationUsageExtraUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReconciliationUsageExtraUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationUsageExtraUpsertOne) SetUpdatedAt(v time.Time) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateUpdatedAt() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ReconciliationUsageExtraUpsertOne) SetUsageLogID(v int64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ReconciliationUsageExtraUpsertOne) AddUsageLogID(v int64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateUsageLogID() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ReconciliationUsageExtraUpsertOne) SetAccountID(v int64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ReconciliationUsageExtraUpsertOne) AddAccountID(v int64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateAccountID() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateAccountID()
	})
}

// SetRuleProvider sets the "rule_provider" field.
func (u *ReconciliationUsageExtraUpsertOne) SetRuleProvider(v string) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRuleProvider(v)
	})
}

// UpdateRuleProvider sets the "rule_provider" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateRuleProvider() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRuleProvider()
	})
}

// SetRuleExternalKey sets the "rule_external_key" field.
func (u *ReconciliationUsageExtraUpsertOne) SetRuleExternalKey(v string) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRuleExternalKey(v)
	})
}

// UpdateRuleExternalKey sets the "rule_external_key" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateRuleExternalKey() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRuleExternalKey()
	})
}

// SetRuleVersion sets the "rule_version" field.
func (u *ReconciliationUsageExtraUpsertOne) SetRuleVersion(v int64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRuleVersion(v)
	})
}

// AddRuleVersion adds v to the "rule_version" field.
func (u *ReconciliationUsageExtraUpsertOne) AddRuleVersion(v int64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddRuleVersion(v)
	})
}

// UpdateRuleVersion sets the "rule_version" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateRuleVersion() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRuleVersion()
	})
}

// SetRevenueOriginal sets the "revenue_original" field.
func (u *ReconciliationUsageExtraUpsertOne) SetRevenueOriginal(v float64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRevenueOriginal(v)
	})
}

// AddRevenueOriginal adds v to the "revenue_original" field.
func (u *ReconciliationUsageExtraUpsertOne) AddRevenueOriginal(v float64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddRevenueOriginal(v)
	})
}

// UpdateRevenueOriginal sets the "revenue_original" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateRevenueOriginal() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRevenueOriginal()
	})
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (u *ReconciliationUsageExtraUpsertOne) SetFxRateToCny(v float64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetFxRateToCny(v)
	})
}

// AddFxRateToCny adds v to the "fx_rate_to_cny" field.
func (u *ReconciliationUsageExtraUpsertOne) AddFxRateToCny(v float64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddFxRateToCny(v)
	})
}

// UpdateFxRateToCny sets the "fx_rate_to_cny" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateFxRateToCny() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateFxRateToCny()
	})
}

// SetRevenueCny sets the "revenue_cny" field.
func (u *ReconciliationUsageExtraUpsertOne) SetRevenueCny(v float64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRevenueCny(v)
	})
}

// AddRevenueCny adds v to the "revenue_cny" field.
func (u *ReconciliationUsageExtraUpsertOne) AddRevenueCny(v float64) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddRevenueCny(v)
	})
}

// UpdateRevenueCny sets the "revenue_cny" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateRevenueCny() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRevenueCny()
	})
}

// SetCollectedAt sets the "collected_at" field.
func (u *ReconciliationUsageExtraUpsertOne) SetCollectedAt(v time.Time) *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetCollectedAt(v)
	})
}

// UpdateCollectedAt sets the "collected_at" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertOne) UpdateCollectedAt() *ReconciliationUsageExtraUpsertOne {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateCollectedAt()
	})
}

// Exec executes the query.
func (u *ReconciliationUsageExtraUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReconciliationUsageExtraCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReconciliationUsageExtraUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReconciliationUsageExtraUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReconciliationUsageExtraUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReconciliationUsageExtraCreateBulk is the builder for creating many ReconciliationUsageExtra entities in bulk.
type ReconciliationUsageExtraCreateBulk struct {
	config
	err      error
	builders []*ReconciliationUsageExtraCreate
	conflict []sql.ConflictOption
}

// Save creates the ReconciliationUsageExtra entities in the database.
func (_c *ReconciliationUsageExtraCreateBulk) Save(ctx context.Context) ([]*ReconciliationUsageExtra, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReconciliationUsageExtra, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReconciliationUsageExtraMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReconciliationUsageExtraCreateBulk) SaveX(ctx context.Context) []*ReconciliationUsageExtra {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationUsageExtraCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationUsageExtraCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReconciliationUsageExtra.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReconciliationUsageExtraUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReconciliationUsageExtraCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReconciliationUsageExtraUpsertBulk {
	_c.conflict = opts
	return &ReconciliationUsageExtraUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReconciliationUsageExtra.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReconciliationUsageExtraCreateBulk) OnConflictColumns(columns ...string) *ReconciliationUsageExtraUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReconciliationUsageExtraUpsertBulk{
		create: _c,
	}
}

// ReconciliationUsageExtraUpsertBulk is the builder for "upsert"-ing
// a bulk of ReconciliationUsageExtra nodes.
type ReconciliationUsageExtraUpsertBulk struct {
	create *ReconciliationUsageExtraCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReconciliationUsageExtra.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReconciliationUsageExtraUpsertBulk) UpdateNewValues() *ReconciliationUsageExtraUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(reconciliationusageextra.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReconciliationUsageExtra.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReconciliationUsageExtraUpsertBulk) Ignore() *ReconciliationUsageExtraUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReconciliationUsageExtraUpsertBulk) DoNothing() *ReconciliationUsageExtraUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReconciliationUsageExtraCreateBulk.OnConflict
// documentation for more info.
func (u *ReconciliationUsageExtraUpsertBulk) Update(set func(*ReconciliationUsageExtraUpsert)) *ReconciliationUsageExtraUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReconciliationUsageExtraUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetUpdatedAt(v time.Time) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateUpdatedAt() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetUsageLogID(v int64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ReconciliationUsageExtraUpsertBulk) AddUsageLogID(v int64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateUsageLogID() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetAccountID(v int64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ReconciliationUsageExtraUpsertBulk) AddAccountID(v int64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateAccountID() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateAccountID()
	})
}

// SetRuleProvider sets the "rule_provider" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetRuleProvider(v string) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRuleProvider(v)
	})
}

// UpdateRuleProvider sets the "rule_provider" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateRuleProvider() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRuleProvider()
	})
}

// SetRuleExternalKey sets the "rule_external_key" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetRuleExternalKey(v string) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRuleExternalKey(v)
	})
}

// UpdateRuleExternalKey sets the "rule_external_key" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateRuleExternalKey() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRuleExternalKey()
	})
}

// SetRuleVersion sets the "rule_version" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetRuleVersion(v int64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRuleVersion(v)
	})
}

// AddRuleVersion adds v to the "rule_version" field.
func (u *ReconciliationUsageExtraUpsertBulk) AddRuleVersion(v int64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddRuleVersion(v)
	})
}

// UpdateRuleVersion sets the "rule_version" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateRuleVersion() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRuleVersion()
	})
}

// SetRevenueOriginal sets the "revenue_original" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetRevenueOriginal(v float64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRevenueOriginal(v)
	})
}

// AddRevenueOriginal adds v to the "revenue_original" field.
func (u *ReconciliationUsageExtraUpsertBulk) AddRevenueOriginal(v float64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddRevenueOriginal(v)
	})
}

// UpdateRevenueOriginal sets the "revenue_original" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateRevenueOriginal() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRevenueOriginal()
	})
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetFxRateToCny(v float64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetFxRateToCny(v)
	})
}

// AddFxRateToCny adds v to the "fx_rate_to_cny" field.
func (u *ReconciliationUsageExtraUpsertBulk) AddFxRateToCny(v float64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddFxRateToCny(v)
	})
}

// UpdateFxRateToCny sets the "fx_rate_to_cny" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateFxRateToCny() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateFxRateToCny()
	})
}

// SetRevenueCny sets the "revenue_cny" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetRevenueCny(v float64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetRevenueCny(v)
	})
}

// AddRevenueCny adds v to the "revenue_cny" field.
func (u *ReconciliationUsageExtraUpsertBulk) AddRevenueCny(v float64) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.AddRevenueCny(v)
	})
}

// UpdateRevenueCny sets the "revenue_cny" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateRevenueCny() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateRevenueCny()
	})
}

// SetCollectedAt sets the "collected_at" field.
func (u *ReconciliationUsageExtraUpsertBulk) SetCollectedAt(v time.Time) *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.SetCollectedAt(v)
	})
}

// UpdateCollectedAt sets the "collected_at" field to the value that was provided on create.
func (u *ReconciliationUsageExtraUpsertBulk) UpdateCollectedAt() *ReconciliationUsageExtraUpsertBulk {
	return u.Update(func(s *ReconciliationUsageExtraUpsert) {
		s.UpdateCollectedAt()
	})
}

// Exec executes the query.
func (u *ReconciliationUsageExtraUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReconciliationUsageExtraCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReconciliationUsageExtraCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReconciliationUsageExtraUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
