// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationusageextra"
)

// ReconciliationUsageExtraUpdate is the builder for updating ReconciliationUsageExtra entities.
type ReconciliationUsageExtraUpdate struct {
	config
	hooks    []Hook
	mutation *ReconciliationUsageExtraMutation
}

// Where appends a list predicates to the ReconciliationUsageExtraUpdate builder.
func (_u *ReconciliationUsageExtraUpdate) Where(ps ...predicate.ReconciliationUsageExtra) *ReconciliationUsageExtraUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationUsageExtraUpdate) SetUpdatedAt(v time.Time) *ReconciliationUsageExtraUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ReconciliationUsageExtraUpdate) SetUsageLogID(v int64) *ReconciliationUsageExtraUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableUsageLogID(v *int64) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ReconciliationUsageExtraUpdate) AddUsageLogID(v int64) *ReconciliationUsageExtraUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ReconciliationUsageExtraUpdate) SetAccountID(v int64) *ReconciliationUsageExtraUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableAccountID(v *int64) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ReconciliationUsageExtraUpdate) AddAccountID(v int64) *ReconciliationUsageExtraUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetRuleProvider sets the "rule_provider" field.
func (_u *ReconciliationUsageExtraUpdate) SetRuleProvider(v string) *ReconciliationUsageExtraUpdate {
	_u.mutation.SetRuleProvider(v)
	return _u
}

// SetNillableRuleProvider sets the "rule_provider" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableRuleProvider(v *string) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetRuleProvider(*v)
	}
	return _u
}

// SetRuleExternalKey sets the "rule_external_key" field.
func (_u *ReconciliationUsageExtraUpdate) SetRuleExternalKey(v string) *ReconciliationUsageExtraUpdate {
	_u.mutation.SetRuleExternalKey(v)
	return _u
}

// SetNillableRuleExternalKey sets the "rule_external_key" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableRuleExternalKey(v *string) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetRuleExternalKey(*v)
	}
	return _u
}

// SetRuleVersion sets the "rule_version" field.
func (_u *ReconciliationUsageExtraUpdate) SetRuleVersion(v int64) *ReconciliationUsageExtraUpdate {
	_u.mutation.ResetRuleVersion()
	_u.mutation.SetRuleVersion(v)
	return _u
}

// SetNillableRuleVersion sets the "rule_version" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableRuleVersion(v *int64) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetRuleVersion(*v)
	}
	return _u
}

// AddRuleVersion adds value to the "rule_version" field.
func (_u *ReconciliationUsageExtraUpdate) AddRuleVersion(v int64) *ReconciliationUsageExtraUpdate {
	_u.mutation.AddRuleVersion(v)
	return _u
}

// SetRevenueOriginal sets the "revenue_original" field.
func (_u *ReconciliationUsageExtraUpdate) SetRevenueOriginal(v float64) *ReconciliationUsageExtraUpdate {
	_u.mutation.ResetRevenueOriginal()
	_u.mutation.SetRevenueOriginal(v)
	return _u
}

// SetNillableRevenueOriginal sets the "revenue_original" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableRevenueOriginal(v *float64) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetRevenueOriginal(*v)
	}
	return _u
}

// AddRevenueOriginal adds value to the "revenue_original" field.
func (_u *ReconciliationUsageExtraUpdate) AddRevenueOriginal(v float64) *ReconciliationUsageExtraUpdate {
	_u.mutation.AddRevenueOriginal(v)
	return _u
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (_u *ReconciliationUsageExtraUpdate) SetFxRateToCny(v float64) *ReconciliationUsageExtraUpdate {
	_u.mutation.ResetFxRateToCny()
	_u.mutation.SetFxRateToCny(v)
	return _u
}

// SetNillableFxRateToCny sets the "fx_rate_to_cny" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableFxRateToCny(v *float64) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetFxRateToCny(*v)
	}
	return _u
}

// AddFxRateToCny adds value to the "fx_rate_to_cny" field.
func (_u *ReconciliationUsageExtraUpdate) AddFxRateToCny(v float64) *ReconciliationUsageExtraUpdate {
	_u.mutation.AddFxRateToCny(v)
	return _u
}

// SetRevenueCny sets the "revenue_cny" field.
func (_u *ReconciliationUsageExtraUpdate) SetRevenueCny(v float64) *ReconciliationUsageExtraUpdate {
	_u.mutation.ResetRevenueCny()
	_u.mutation.SetRevenueCny(v)
	return _u
}

// SetNillableRevenueCny sets the "revenue_cny" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableRevenueCny(v *float64) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetRevenueCny(*v)
	}
	return _u
}

// AddRevenueCny adds value to the "revenue_cny" field.
func (_u *ReconciliationUsageExtraUpdate) AddRevenueCny(v float64) *ReconciliationUsageExtraUpdate {
	_u.mutation.AddRevenueCny(v)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *ReconciliationUsageExtraUpdate) SetCollectedAt(v time.Time) *ReconciliationUsageExtraUpdate {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdate) SetNillableCollectedAt(v *time.Time) *ReconciliationUsageExtraUpdate {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// Mutation returns the ReconciliationUsageExtraMutation object of the builder.
func (_u *ReconciliationUsageExtraUpdate) Mutation() *ReconciliationUsageExtraMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReconciliationUsageExtraUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationUsageExtraUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReconciliationUsageExtraUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationUsageExtraUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationUsageExtraUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationusageextra.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationUsageExtraUpdate) check() error {
	if v, ok := _u.mutation.RuleProvider(); ok {
		if err := reconciliationusageextra.RuleProviderValidator(v); err != nil {
			return &ValidationError{Name: "rule_provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUsageExtra.rule_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleExternalKey(); ok {
		if err := reconciliationusageextra.RuleExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "rule_external_key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUsageExtra.rule_external_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationUsageExtraUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationusageextra.Table, reconciliationusageextra.Columns, sqlgraph.NewFieldSpec(reconciliationusageextra.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(reconciliationusageextra.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(reconciliationusageextra.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(reconciliationusageextra.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(reconciliationusageextra.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RuleProvider(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleExternalKey(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleExternalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleVersion(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRuleVersion(); ok {
		_spec.AddField(reconciliationusageextra.FieldRuleVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RevenueOriginal(); ok {
		_spec.SetField(reconciliationusageextra.FieldRevenueOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRevenueOriginal(); ok {
		_spec.AddField(reconciliationusageextra.FieldRevenueOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FxRateToCny(); ok {
		_spec.SetField(reconciliationusageextra.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFxRateToCny(); ok {
		_spec.AddField(reconciliationusageextra.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RevenueCny(); ok {
		_spec.SetField(reconciliationusageextra.FieldRevenueCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRevenueCny(); ok {
		_spec.AddField(reconciliationusageextra.FieldRevenueCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldCollectedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationusageextra.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReconciliationUsageExtraUpdateOne is the builder for updating a single ReconciliationUsageExtra entity.
type ReconciliationUsageExtraUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReconciliationUsageExtraMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetUpdatedAt(v time.Time) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetUsageLogID(v int64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableUsageLogID(v *int64) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ReconciliationUsageExtraUpdateOne) AddUsageLogID(v int64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetAccountID(v int64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableAccountID(v *int64) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ReconciliationUsageExtraUpdateOne) AddAccountID(v int64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetRuleProvider sets the "rule_provider" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetRuleProvider(v string) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.SetRuleProvider(v)
	return _u
}

// SetNillableRuleProvider sets the "rule_provider" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableRuleProvider(v *string) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetRuleProvider(*v)
	}
	return _u
}

// SetRuleExternalKey sets the "rule_external_key" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetRuleExternalKey(v string) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.SetRuleExternalKey(v)
	return _u
}

// SetNillableRuleExternalKey sets the "rule_external_key" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableRuleExternalKey(v *string) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetRuleExternalKey(*v)
	}
	return _u
}

// SetRuleVersion sets the "rule_version" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetRuleVersion(v int64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.ResetRuleVersion()
	_u.mutation.SetRuleVersion(v)
	return _u
}

// SetNillableRuleVersion sets the "rule_version" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableRuleVersion(v *int64) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetRuleVersion(*v)
	}
	return _u
}

// AddRuleVersion adds value to the "rule_version" field.
func (_u *ReconciliationUsageExtraUpdateOne) AddRuleVersion(v int64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.AddRuleVersion(v)
	return _u
}

// SetRevenueOriginal sets the "revenue_original" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetRevenueOriginal(v float64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.ResetRevenueOriginal()
	_u.mutation.SetRevenueOriginal(v)
	return _u
}

// SetNillableRevenueOriginal sets the "revenue_original" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableRevenueOriginal(v *float64) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetRevenueOriginal(*v)
	}
	return _u
}

// AddRevenueOriginal adds value to the "revenue_original" field.
func (_u *ReconciliationUsageExtraUpdateOne) AddRevenueOriginal(v float64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.AddRevenueOriginal(v)
	return _u
}

// SetFxRateToCny sets the "fx_rate_to_cny" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetFxRateToCny(v float64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.ResetFxRateToCny()
	_u.mutation.SetFxRateToCny(v)
	return _u
}

// SetNillableFxRateToCny sets the "fx_rate_to_cny" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableFxRateToCny(v *float64) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetFxRateToCny(*v)
	}
	return _u
}

// AddFxRateToCny adds value to the "fx_rate_to_cny" field.
func (_u *ReconciliationUsageExtraUpdateOne) AddFxRateToCny(v float64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.AddFxRateToCny(v)
	return _u
}

// SetRevenueCny sets the "revenue_cny" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetRevenueCny(v float64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.ResetRevenueCny()
	_u.mutation.SetRevenueCny(v)
	return _u
}

// SetNillableRevenueCny sets the "revenue_cny" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableRevenueCny(v *float64) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetRevenueCny(*v)
	}
	return _u
}

// AddRevenueCny adds value to the "revenue_cny" field.
func (_u *ReconciliationUsageExtraUpdateOne) AddRevenueCny(v float64) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.AddRevenueCny(v)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *ReconciliationUsageExtraUpdateOne) SetCollectedAt(v time.Time) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *ReconciliationUsageExtraUpdateOne) SetNillableCollectedAt(v *time.Time) *ReconciliationUsageExtraUpdateOne {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// Mutation returns the ReconciliationUsageExtraMutation object of the builder.
func (_u *ReconciliationUsageExtraUpdateOne) Mutation() *ReconciliationUsageExtraMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReconciliationUsageExtraUpdate builder.
func (_u *ReconciliationUsageExtraUpdateOne) Where(ps ...predicate.ReconciliationUsageExtra) *ReconciliationUsageExtraUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReconciliationUsageExtraUpdateOne) Select(field string, fields ...string) *ReconciliationUsageExtraUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReconciliationUsageExtra entity.
func (_u *ReconciliationUsageExtraUpdateOne) Save(ctx context.Context) (*ReconciliationUsageExtra, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReconciliationUsageExtraUpdateOne) SaveX(ctx context.Context) *ReconciliationUsageExtra {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReconciliationUsageExtraUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReconciliationUsageExtraUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReconciliationUsageExtraUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reconciliationusageextra.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReconciliationUsageExtraUpdateOne) check() error {
	if v, ok := _u.mutation.RuleProvider(); ok {
		if err := reconciliationusageextra.RuleProviderValidator(v); err != nil {
			return &ValidationError{Name: "rule_provider", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUsageExtra.rule_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleExternalKey(); ok {
		if err := reconciliationusageextra.RuleExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "rule_external_key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationUsageExtra.rule_external_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ReconciliationUsageExtraUpdateOne) sqlSave(ctx context.Context) (_node *ReconciliationUsageExtra, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reconciliationusageextra.Table, reconciliationusageextra.Columns, sqlgraph.NewFieldSpec(reconciliationusageextra.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReconciliationUsageExtra.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reconciliationusageextra.FieldID)
		for _, f := range fields {
			if !reconciliationusageextra.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reconciliationusageextra.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(reconciliationusageextra.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(reconciliationusageextra.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(reconciliationusageextra.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(reconciliationusageextra.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RuleProvider(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleExternalKey(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleExternalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleVersion(); ok {
		_spec.SetField(reconciliationusageextra.FieldRuleVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRuleVersion(); ok {
		_spec.AddField(reconciliationusageextra.FieldRuleVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RevenueOriginal(); ok {
		_spec.SetField(reconciliationusageextra.FieldRevenueOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRevenueOriginal(); ok {
		_spec.AddField(reconciliationusageextra.FieldRevenueOriginal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FxRateToCny(); ok {
		_spec.SetField(reconciliationusageextra.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFxRateToCny(); ok {
		_spec.AddField(reconciliationusageextra.FieldFxRateToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RevenueCny(); ok {
		_spec.SetField(reconciliationusageextra.FieldRevenueCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRevenueCny(); ok {
		_spec.AddField(reconciliationusageextra.FieldRevenueCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(reconciliationusageextra.FieldCollectedAt, field.TypeTime, value)
	}
	_node = &ReconciliationUsageExtra{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reconciliationusageextra.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
