// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationusageextra"
)

// ReconciliationUsageExtra is the model entity for the ReconciliationUsageExtra schema.
type ReconciliationUsageExtra struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 对应 usage_logs.id
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// 调用使用的账号 ID，冗余用于按账号聚合
	AccountID int64 `json:"account_id,omitempty"`
	// 采集时的规则来源，空串表示当时该账号没有规则
	RuleProvider string `json:"rule_provider,omitempty"`
	// 采集时的上游令牌名，用于令牌改名后回查历史账单
	RuleExternalKey string `json:"rule_external_key,omitempty"`
	// 采集时的规则版本号
	RuleVersion int64 `json:"rule_version,omitempty"`
	// 下游收入原值（usage_logs.actual_cost 的快照）
	RevenueOriginal float64 `json:"revenue_original,omitempty"`
	// 采集时的美元->人民币换算数字快照
	FxRateToCny float64 `json:"fx_rate_to_cny,omitempty"`
	// 换算后的下游收入，落库即冻结
	RevenueCny float64 `json:"revenue_cny,omitempty"`
	// 采集时间
	CollectedAt  time.Time `json:"collected_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReconciliationUsageExtra) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reconciliationusageextra.FieldRevenueOriginal, reconciliationusageextra.FieldFxRateToCny, reconciliationusageextra.FieldRevenueCny:
			values[i] = new(sql.NullFloat64)
		case reconciliationusageextra.FieldID, reconciliationusageextra.FieldUsageLogID, reconciliationusageextra.FieldAccountID, reconciliationusageextra.FieldRuleVersion:
			values[i] = new(sql.NullInt64)
		case reconciliationusageextra.FieldRuleProvider, reconciliationusageextra.FieldRuleExternalKey:
			values[i] = new(sql.NullString)
		case reconciliationusageextra.FieldCreatedAt, reconciliationusageextra.FieldUpdatedAt, reconciliationusageextra.FieldCollectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReconciliationUsageExtra fields.
func (_m *ReconciliationUsageExtra) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reconciliationusageextra.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case reconciliationusageextra.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reconciliationusageextra.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case reconciliationusageextra.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case reconciliationusageextra.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case reconciliationusageextra.FieldRuleProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_provider", values[i])
			} else if value.Valid {
				_m.RuleProvider = value.String
			}
		case reconciliationusageextra.FieldRuleExternalKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_external_key", values[i])
			} else if value.Valid {
				_m.RuleExternalKey = value.String
			}
		case reconciliationusageextra.FieldRuleVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_version", values[i])
			} else if value.Valid {
				_m.RuleVersion = value.Int64
			}
		case reconciliationusageextra.FieldRevenueOriginal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field revenue_original", values[i])
			} else if value.Valid {
				_m.RevenueOriginal = value.Float64
			}
		case reconciliationusageextra.FieldFxRateToCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fx_rate_to_cny", values[i])
			} else if value.Valid {
				_m.FxRateToCny = value.Float64
			}
		case reconciliationusageextra.FieldRevenueCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field revenue_cny", values[i])
			} else if value.Valid {
				_m.RevenueCny = value.Float64
			}
		case reconciliationusageextra.FieldCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field collected_at", values[i])
			} else if value.Valid {
				_m.CollectedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReconciliationUsageExtra.
// This includes values selected through modifiers, order, etc.
func (_m *ReconciliationUsageExtra) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReconciliationUsageExtra.
// Note that you need to call ReconciliationUsageExtra.Unwrap() before calling this method if this ReconciliationUsageExtra
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReconciliationUsageExtra) Update() *ReconciliationUsageExtraUpdateOne {
	return NewReconciliationUsageExtraClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReconciliationUsageExtra entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReconciliationUsageExtra) Unwrap() *ReconciliationUsageExtra {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReconciliationUsageExtra is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReconciliationUsageExtra) String() string {
	var builder strings.Builder
	builder.WriteString("ReconciliationUsageExtra(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("rule_provider=")
	builder.WriteString(_m.RuleProvider)
	builder.WriteString(", ")
	builder.WriteString("rule_external_key=")
	builder.WriteString(_m.RuleExternalKey)
	builder.WriteString(", ")
	builder.WriteString("rule_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RuleVersion))
	builder.WriteString(", ")
	builder.WriteString("revenue_original=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevenueOriginal))
	builder.WriteString(", ")
	builder.WriteString("fx_rate_to_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.FxRateToCny))
	builder.WriteString(", ")
	builder.WriteString("revenue_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevenueCny))
	builder.WriteString(", ")
	builder.WriteString("collected_at=")
	builder.WriteString(_m.CollectedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReconciliationUsageExtras is a parsable slice of ReconciliationUsageExtra.
type ReconciliationUsageExtras []*ReconciliationUsageExtra
