// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/reconciliationsyncstate"
)

// ReconciliationSyncStateCreate is the builder for creating a ReconciliationSyncState entity.
type ReconciliationSyncStateCreate struct {
	config
	mutation *ReconciliationSyncStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *ReconciliationSyncStateCreate) SetKey(v string) *ReconciliationSyncStateCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *ReconciliationSyncStateCreate) SetValue(v string) *ReconciliationSyncStateCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *ReconciliationSyncStateCreate) SetNillableValue(v *string) *ReconciliationSyncStateCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReconciliationSyncStateCreate) SetUpdatedAt(v time.Time) *ReconciliationSyncStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReconciliationSyncStateCreate) SetNillableUpdatedAt(v *time.Time) *ReconciliationSyncStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ReconciliationSyncStateMutation object of the builder.
func (_c *ReconciliationSyncStateCreate) Mutation() *ReconciliationSyncStateMutation {
	return _c.mutation
}

// Save creates the ReconciliationSyncState in the database.
func (_c *ReconciliationSyncStateCreate) Save(ctx context.Context) (*ReconciliationSyncState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReconciliationSyncStateCreate) SaveX(ctx context.Context) *ReconciliationSyncState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationSyncStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationSyncStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReconciliationSyncStateCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := reconciliationsyncstate.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := reconciliationsyncstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReconciliationSyncStateCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ReconciliationSyncState.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := reconciliationsyncstate.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ReconciliationSyncState.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "ReconciliationSyncState.value"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReconciliationSyncState.updated_at"`)}
	}
	return nil
}

func (_c *ReconciliationSyncStateCreate) sqlSave(ctx context.Context) (*ReconciliationSyncState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReconciliationSyncStateCreate) createSpec() (*ReconciliationSyncState, *sqlgraph.CreateSpec) {
	var (
		_node = &ReconciliationSyncState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reconciliationsyncstate.Table, sqlgraph.NewFieldSpec(reconciliationsyncstate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(reconciliationsyncstate.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(reconciliationsyncstate.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliationsyncstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReconciliationSyncState.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReconciliationSyncStateUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ReconciliationSyncStateCreate) OnConflict(opts ...sql.ConflictOption) *ReconciliationSyncStateUpsertOne {
	_c.conflict = opts
	return &ReconciliationSyncStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReconciliationSyncState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReconciliationSyncStateCreate) OnConflictColumns(columns ...string) *ReconciliationSyncStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReconciliationSyncStateUpsertOne{
		create: _c,
	}
}

type (
	// ReconciliationSyncStateUpsertOne is the builder for "upsert"-ing
	//  one ReconciliationSyncState node.
	ReconciliationSyncStateUpsertOne struct {
		create *ReconciliationSyncStateCreate
	}

	// ReconciliationSyncStateUpsert is the "OnConflict" setter.
	ReconciliationSyncStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *ReconciliationSyncStateUpsert) SetKey(v string) *ReconciliationSyncStateUpsert {
	u.Set(reconciliationsyncstate.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsert) UpdateKey() *ReconciliationSyncStateUpsert {
	u.SetExcluded(reconciliationsyncstate.FieldKey)
	return u
}

// SetValue sets the "value" field.
func (u *ReconciliationSyncStateUpsert) SetValue(v string) *ReconciliationSyncStateUpsert {
	u.Set(reconciliationsyncstate.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsert) UpdateValue() *ReconciliationSyncStateUpsert {
	u.SetExcluded(reconciliationsyncstate.FieldValue)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationSyncStateUpsert) SetUpdatedAt(v time.Time) *ReconciliationSyncStateUpsert {
	u.Set(reconciliationsyncstate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsert) UpdateUpdatedAt() *ReconciliationSyncStateUpsert {
	u.SetExcluded(reconciliationsyncstate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReconciliationSyncState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReconciliationSyncStateUpsertOne) UpdateNewValues() *ReconciliationSyncStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReconciliationSyncState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReconciliationSyncStateUpsertOne) Ignore() *ReconciliationSyncStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReconciliationSyncStateUpsertOne) DoNothing() *ReconciliationSyncStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReconciliationSyncStateCreate.OnConflict
// documentation for more info.
func (u *ReconciliationSyncStateUpsertOne) Update(set func(*ReconciliationSyncStateUpsert)) *ReconciliationSyncStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReconciliationSyncStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ReconciliationSyncStateUpsertOne) SetKey(v string) *ReconciliationSyncStateUpsertOne {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsertOne) UpdateKey() *ReconciliationSyncStateUpsertOne {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *ReconciliationSyncStateUpsertOne) SetValue(v string) *ReconciliationSyncStateUpsertOne {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsertOne) UpdateValue() *ReconciliationSyncStateUpsertOne {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationSyncStateUpsertOne) SetUpdatedAt(v time.Time) *ReconciliationSyncStateUpsertOne {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsertOne) UpdateUpdatedAt() *ReconciliationSyncStateUpsertOne {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReconciliationSyncStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReconciliationSyncStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReconciliationSyncStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReconciliationSyncStateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReconciliationSyncStateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReconciliationSyncStateCreateBulk is the builder for creating many ReconciliationSyncState entities in bulk.
type ReconciliationSyncStateCreateBulk struct {
	config
	err      error
	builders []*ReconciliationSyncStateCreate
	conflict []sql.ConflictOption
}

// Save creates the ReconciliationSyncState entities in the database.
func (_c *ReconciliationSyncStateCreateBulk) Save(ctx context.Context) ([]*ReconciliationSyncState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReconciliationSyncState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReconciliationSyncStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReconciliationSyncStateCreateBulk) SaveX(ctx context.Context) []*ReconciliationSyncState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationSyncStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationSyncStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReconciliationSyncState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReconciliationSyncStateUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ReconciliationSyncStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReconciliationSyncStateUpsertBulk {
	_c.conflict = opts
	return &ReconciliationSyncStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReconciliationSyncState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReconciliationSyncStateCreateBulk) OnConflictColumns(columns ...string) *ReconciliationSyncStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReconciliationSyncStateUpsertBulk{
		create: _c,
	}
}

// ReconciliationSyncStateUpsertBulk is the builder for "upsert"-ing
// a bulk of ReconciliationSyncState nodes.
type ReconciliationSyncStateUpsertBulk struct {
	create *ReconciliationSyncStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReconciliationSyncState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReconciliationSyncStateUpsertBulk) UpdateNewValues() *ReconciliationSyncStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReconciliationSyncState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReconciliationSyncStateUpsertBulk) Ignore() *ReconciliationSyncStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReconciliationSyncStateUpsertBulk) DoNothing() *ReconciliationSyncStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReconciliationSyncStateCreateBulk.OnConflict
// documentation for more info.
func (u *ReconciliationSyncStateUpsertBulk) Update(set func(*ReconciliationSyncStateUpsert)) *ReconciliationSyncStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReconciliationSyncStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ReconciliationSyncStateUpsertBulk) SetKey(v string) *ReconciliationSyncStateUpsertBulk {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsertBulk) UpdateKey() *ReconciliationSyncStateUpsertBulk {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *ReconciliationSyncStateUpsertBulk) SetValue(v string) *ReconciliationSyncStateUpsertBulk {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsertBulk) UpdateValue() *ReconciliationSyncStateUpsertBulk {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReconciliationSyncStateUpsertBulk) SetUpdatedAt(v time.Time) *ReconciliationSyncStateUpsertBulk {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReconciliationSyncStateUpsertBulk) UpdateUpdatedAt() *ReconciliationSyncStateUpsertBulk {
	return u.Update(func(s *ReconciliationSyncStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReconciliationSyncStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReconciliationSyncStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReconciliationSyncStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReconciliationSyncStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
