// Code generated by ent, DO NOT EDIT.

package reconciliationaccountrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldAccountID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldProvider, v))
}

// ExternalKey applies equality check predicate on the "external_key" field. It's identical to ExternalKeyEQ.
func ExternalKey(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldExternalKey, v))
}

// Multiplier applies equality check predicate on the "multiplier" field. It's identical to MultiplierEQ.
func Multiplier(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldMultiplier, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldVersion, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldAccountID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldContainsFold(FieldProvider, v))
}

// ExternalKeyEQ applies the EQ predicate on the "external_key" field.
func ExternalKeyEQ(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldExternalKey, v))
}

// ExternalKeyNEQ applies the NEQ predicate on the "external_key" field.
func ExternalKeyNEQ(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldExternalKey, v))
}

// ExternalKeyIn applies the In predicate on the "external_key" field.
func ExternalKeyIn(vs ...string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldExternalKey, vs...))
}

// ExternalKeyNotIn applies the NotIn predicate on the "external_key" field.
func ExternalKeyNotIn(vs ...string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldExternalKey, vs...))
}

// ExternalKeyGT applies the GT predicate on the "external_key" field.
func ExternalKeyGT(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldExternalKey, v))
}

// ExternalKeyGTE applies the GTE predicate on the "external_key" field.
func ExternalKeyGTE(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldExternalKey, v))
}

// ExternalKeyLT applies the LT predicate on the "external_key" field.
func ExternalKeyLT(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldExternalKey, v))
}

// ExternalKeyLTE applies the LTE predicate on the "external_key" field.
func ExternalKeyLTE(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldExternalKey, v))
}

// ExternalKeyContains applies the Contains predicate on the "external_key" field.
func ExternalKeyContains(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldContains(FieldExternalKey, v))
}

// ExternalKeyHasPrefix applies the HasPrefix predicate on the "external_key" field.
func ExternalKeyHasPrefix(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldHasPrefix(FieldExternalKey, v))
}

// ExternalKeyHasSuffix applies the HasSuffix predicate on the "external_key" field.
func ExternalKeyHasSuffix(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldHasSuffix(FieldExternalKey, v))
}

// ExternalKeyEqualFold applies the EqualFold predicate on the "external_key" field.
func ExternalKeyEqualFold(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEqualFold(FieldExternalKey, v))
}

// ExternalKeyContainsFold applies the ContainsFold predicate on the "external_key" field.
func ExternalKeyContainsFold(v string) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldContainsFold(FieldExternalKey, v))
}

// MultiplierEQ applies the EQ predicate on the "multiplier" field.
func MultiplierEQ(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldMultiplier, v))
}

// MultiplierNEQ applies the NEQ predicate on the "multiplier" field.
func MultiplierNEQ(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldMultiplier, v))
}

// MultiplierIn applies the In predicate on the "multiplier" field.
func MultiplierIn(vs ...float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldMultiplier, vs...))
}

// MultiplierNotIn applies the NotIn predicate on the "multiplier" field.
func MultiplierNotIn(vs ...float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldMultiplier, vs...))
}

// MultiplierGT applies the GT predicate on the "multiplier" field.
func MultiplierGT(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldMultiplier, v))
}

// MultiplierGTE applies the GTE predicate on the "multiplier" field.
func MultiplierGTE(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldMultiplier, v))
}

// MultiplierLT applies the LT predicate on the "multiplier" field.
func MultiplierLT(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldMultiplier, v))
}

// MultiplierLTE applies the LTE predicate on the "multiplier" field.
func MultiplierLTE(v float64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldMultiplier, v))
}

// MultiplierIsNil applies the IsNil predicate on the "multiplier" field.
func MultiplierIsNil() predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIsNull(FieldMultiplier))
}

// MultiplierNotNil applies the NotNil predicate on the "multiplier" field.
func MultiplierNotNil() predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotNull(FieldMultiplier))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldLTE(FieldVersion, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReconciliationAccountRule) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReconciliationAccountRule) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReconciliationAccountRule) predicate.ReconciliationAccountRule {
	return predicate.ReconciliationAccountRule(sql.NotPredicates(p))
}
