// Code generated by ent, DO NOT EDIT.

package reconciliationupstreambill

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the reconciliationupstreambill type in the database.
	Label = "reconciliation_upstream_bill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldUpstreamRequestID holds the string denoting the upstream_request_id field in the database.
	FieldUpstreamRequestID = "upstream_request_id"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// FieldBillingDate holds the string denoting the billing_date field in the database.
	FieldBillingDate = "billing_date"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldTokenName holds the string denoting the token_name field in the database.
	FieldTokenName = "token_name"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldCacheCreationTokens holds the string denoting the cache_creation_tokens field in the database.
	FieldCacheCreationTokens = "cache_creation_tokens"
	// FieldCacheTokensTotal holds the string denoting the cache_tokens_total field in the database.
	FieldCacheTokensTotal = "cache_tokens_total"
	// FieldCostOriginal holds the string denoting the cost_original field in the database.
	FieldCostOriginal = "cost_original"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldFxRateToCny holds the string denoting the fx_rate_to_cny field in the database.
	FieldFxRateToCny = "fx_rate_to_cny"
	// FieldCostCny holds the string denoting the cost_cny field in the database.
	FieldCostCny = "cost_cny"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldMatchState holds the string denoting the match_state field in the database.
	FieldMatchState = "match_state"
	// FieldMatchMethod holds the string denoting the match_method field in the database.
	FieldMatchMethod = "match_method"
	// FieldMatchedUsageLogID holds the string denoting the matched_usage_log_id field in the database.
	FieldMatchedUsageLogID = "matched_usage_log_id"
	// FieldMatchedAccountID holds the string denoting the matched_account_id field in the database.
	FieldMatchedAccountID = "matched_account_id"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// FieldImportedAt holds the string denoting the imported_at field in the database.
	FieldImportedAt = "imported_at"
	// Table holds the table name of the reconciliationupstreambill in the database.
	Table = "reconciliation_upstream_bills"
)

// Columns holds all SQL columns for reconciliationupstreambill fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProvider,
	FieldUpstreamRequestID,
	FieldOccurredAt,
	FieldBillingDate,
	FieldModel,
	FieldTokenName,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCacheReadTokens,
	FieldCacheCreationTokens,
	FieldCacheTokensTotal,
	FieldCostOriginal,
	FieldCurrency,
	FieldFxRateToCny,
	FieldCostCny,
	FieldSource,
	FieldMatchState,
	FieldMatchMethod,
	FieldMatchedUsageLogID,
	FieldMatchedAccountID,
	FieldRaw,
	FieldImportedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// UpstreamRequestIDValidator is a validator for the "upstream_request_id" field. It is called by the builders before save.
	UpstreamRequestIDValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultTokenName holds the default value on creation for the "token_name" field.
	DefaultTokenName string
	// TokenNameValidator is a validator for the "token_name" field. It is called by the builders before save.
	TokenNameValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int
	// DefaultCacheCreationTokens holds the default value on creation for the "cache_creation_tokens" field.
	DefaultCacheCreationTokens int
	// DefaultCacheTokensTotal holds the default value on creation for the "cache_tokens_total" field.
	DefaultCacheTokensTotal int
	// DefaultCostOriginal holds the default value on creation for the "cost_original" field.
	DefaultCostOriginal float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultFxRateToCny holds the default value on creation for the "fx_rate_to_cny" field.
	DefaultFxRateToCny float64
	// DefaultCostCny holds the default value on creation for the "cost_cny" field.
	DefaultCostCny float64
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultMatchState holds the default value on creation for the "match_state" field.
	DefaultMatchState string
	// MatchStateValidator is a validator for the "match_state" field. It is called by the builders before save.
	MatchStateValidator func(string) error
	// DefaultMatchMethod holds the default value on creation for the "match_method" field.
	DefaultMatchMethod string
	// MatchMethodValidator is a validator for the "match_method" field. It is called by the builders before save.
	MatchMethodValidator func(string) error
	// DefaultImportedAt holds the default value on creation for the "imported_at" field.
	DefaultImportedAt func() time.Time
)

// OrderOption defines the ordering options for the ReconciliationUpstreamBill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByUpstreamRequestID orders the results by the upstream_request_id field.
func ByUpstreamRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRequestID, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByBillingDate orders the results by the billing_date field.
func ByBillingDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingDate, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByTokenName orders the results by the token_name field.
func ByTokenName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenName, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByCacheCreationTokens orders the results by the cache_creation_tokens field.
func ByCacheCreationTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationTokens, opts...).ToFunc()
}

// ByCacheTokensTotal orders the results by the cache_tokens_total field.
func ByCacheTokensTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheTokensTotal, opts...).ToFunc()
}

// ByCostOriginal orders the results by the cost_original field.
func ByCostOriginal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostOriginal, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByFxRateToCny orders the results by the fx_rate_to_cny field.
func ByFxRateToCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFxRateToCny, opts...).ToFunc()
}

// ByCostCny orders the results by the cost_cny field.
func ByCostCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostCny, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByMatchState orders the results by the match_state field.
func ByMatchState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchState, opts...).ToFunc()
}

// ByMatchMethod orders the results by the match_method field.
func ByMatchMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchMethod, opts...).ToFunc()
}

// ByMatchedUsageLogID orders the results by the matched_usage_log_id field.
func ByMatchedUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedUsageLogID, opts...).ToFunc()
}

// ByMatchedAccountID orders the results by the matched_account_id field.
func ByMatchedAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedAccountID, opts...).ToFunc()
}

// ByImportedAt orders the results by the imported_at field.
func ByImportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedAt, opts...).ToFunc()
}
