// Code generated by ent, DO NOT EDIT.

package reconciliationupstreambill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldUpdatedAt, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldProvider, v))
}

// UpstreamRequestID applies equality check predicate on the "upstream_request_id" field. It's identical to UpstreamRequestIDEQ.
func UpstreamRequestID(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldOccurredAt, v))
}

// BillingDate applies equality check predicate on the "billing_date" field. It's identical to BillingDateEQ.
func BillingDate(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldBillingDate, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldModel, v))
}

// TokenName applies equality check predicate on the "token_name" field. It's identical to TokenNameEQ.
func TokenName(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldTokenName, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheTokensTotal applies equality check predicate on the "cache_tokens_total" field. It's identical to CacheTokensTotalEQ.
func CacheTokensTotal(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCacheTokensTotal, v))
}

// CostOriginal applies equality check predicate on the "cost_original" field. It's identical to CostOriginalEQ.
func CostOriginal(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCostOriginal, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCurrency, v))
}

// FxRateToCny applies equality check predicate on the "fx_rate_to_cny" field. It's identical to FxRateToCnyEQ.
func FxRateToCny(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldFxRateToCny, v))
}

// CostCny applies equality check predicate on the "cost_cny" field. It's identical to CostCnyEQ.
func CostCny(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCostCny, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldSource, v))
}

// MatchState applies equality check predicate on the "match_state" field. It's identical to MatchStateEQ.
func MatchState(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchState, v))
}

// MatchMethod applies equality check predicate on the "match_method" field. It's identical to MatchMethodEQ.
func MatchMethod(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchMethod, v))
}

// MatchedUsageLogID applies equality check predicate on the "matched_usage_log_id" field. It's identical to MatchedUsageLogIDEQ.
func MatchedUsageLogID(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchedUsageLogID, v))
}

// MatchedAccountID applies equality check predicate on the "matched_account_id" field. It's identical to MatchedAccountIDEQ.
func MatchedAccountID(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchedAccountID, v))
}

// ImportedAt applies equality check predicate on the "imported_at" field. It's identical to ImportedAtEQ.
func ImportedAt(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldImportedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldProvider, v))
}

// UpstreamRequestIDEQ applies the EQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDNEQ applies the NEQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIn applies the In predicate on the "upstream_request_id" field.
func UpstreamRequestIDIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDNotIn applies the NotIn predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDGT applies the GT predicate on the "upstream_request_id" field.
func UpstreamRequestIDGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDGTE applies the GTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLT applies the LT predicate on the "upstream_request_id" field.
func UpstreamRequestIDLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLTE applies the LTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContains applies the Contains predicate on the "upstream_request_id" field.
func UpstreamRequestIDContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasPrefix applies the HasPrefix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasSuffix applies the HasSuffix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDEqualFold applies the EqualFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContainsFold applies the ContainsFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldUpstreamRequestID, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldOccurredAt, v))
}

// BillingDateEQ applies the EQ predicate on the "billing_date" field.
func BillingDateEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldBillingDate, v))
}

// BillingDateNEQ applies the NEQ predicate on the "billing_date" field.
func BillingDateNEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldBillingDate, v))
}

// BillingDateIn applies the In predicate on the "billing_date" field.
func BillingDateIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldBillingDate, vs...))
}

// BillingDateNotIn applies the NotIn predicate on the "billing_date" field.
func BillingDateNotIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldBillingDate, vs...))
}

// BillingDateGT applies the GT predicate on the "billing_date" field.
func BillingDateGT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldBillingDate, v))
}

// BillingDateGTE applies the GTE predicate on the "billing_date" field.
func BillingDateGTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldBillingDate, v))
}

// BillingDateLT applies the LT predicate on the "billing_date" field.
func BillingDateLT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldBillingDate, v))
}

// BillingDateLTE applies the LTE predicate on the "billing_date" field.
func BillingDateLTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldBillingDate, v))
}

// BillingDateIsNil applies the IsNil predicate on the "billing_date" field.
func BillingDateIsNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIsNull(FieldBillingDate))
}

// BillingDateNotNil applies the NotNil predicate on the "billing_date" field.
func BillingDateNotNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotNull(FieldBillingDate))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldModel, v))
}

// TokenNameEQ applies the EQ predicate on the "token_name" field.
func TokenNameEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldTokenName, v))
}

// TokenNameNEQ applies the NEQ predicate on the "token_name" field.
func TokenNameNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldTokenName, v))
}

// TokenNameIn applies the In predicate on the "token_name" field.
func TokenNameIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldTokenName, vs...))
}

// TokenNameNotIn applies the NotIn predicate on the "token_name" field.
func TokenNameNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldTokenName, vs...))
}

// TokenNameGT applies the GT predicate on the "token_name" field.
func TokenNameGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldTokenName, v))
}

// TokenNameGTE applies the GTE predicate on the "token_name" field.
func TokenNameGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldTokenName, v))
}

// TokenNameLT applies the LT predicate on the "token_name" field.
func TokenNameLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldTokenName, v))
}

// TokenNameLTE applies the LTE predicate on the "token_name" field.
func TokenNameLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldTokenName, v))
}

// TokenNameContains applies the Contains predicate on the "token_name" field.
func TokenNameContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldTokenName, v))
}

// TokenNameHasPrefix applies the HasPrefix predicate on the "token_name" field.
func TokenNameHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldTokenName, v))
}

// TokenNameHasSuffix applies the HasSuffix predicate on the "token_name" field.
func TokenNameHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldTokenName, v))
}

// TokenNameEqualFold applies the EqualFold predicate on the "token_name" field.
func TokenNameEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldTokenName, v))
}

// TokenNameContainsFold applies the ContainsFold predicate on the "token_name" field.
func TokenNameContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldTokenName, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCacheReadTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CacheTokensTotalEQ applies the EQ predicate on the "cache_tokens_total" field.
func CacheTokensTotalEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCacheTokensTotal, v))
}

// CacheTokensTotalNEQ applies the NEQ predicate on the "cache_tokens_total" field.
func CacheTokensTotalNEQ(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCacheTokensTotal, v))
}

// CacheTokensTotalIn applies the In predicate on the "cache_tokens_total" field.
func CacheTokensTotalIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCacheTokensTotal, vs...))
}

// CacheTokensTotalNotIn applies the NotIn predicate on the "cache_tokens_total" field.
func CacheTokensTotalNotIn(vs ...int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCacheTokensTotal, vs...))
}

// CacheTokensTotalGT applies the GT predicate on the "cache_tokens_total" field.
func CacheTokensTotalGT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCacheTokensTotal, v))
}

// CacheTokensTotalGTE applies the GTE predicate on the "cache_tokens_total" field.
func CacheTokensTotalGTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCacheTokensTotal, v))
}

// CacheTokensTotalLT applies the LT predicate on the "cache_tokens_total" field.
func CacheTokensTotalLT(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCacheTokensTotal, v))
}

// CacheTokensTotalLTE applies the LTE predicate on the "cache_tokens_total" field.
func CacheTokensTotalLTE(v int) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCacheTokensTotal, v))
}

// CostOriginalEQ applies the EQ predicate on the "cost_original" field.
func CostOriginalEQ(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCostOriginal, v))
}

// CostOriginalNEQ applies the NEQ predicate on the "cost_original" field.
func CostOriginalNEQ(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCostOriginal, v))
}

// CostOriginalIn applies the In predicate on the "cost_original" field.
func CostOriginalIn(vs ...float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCostOriginal, vs...))
}

// CostOriginalNotIn applies the NotIn predicate on the "cost_original" field.
func CostOriginalNotIn(vs ...float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCostOriginal, vs...))
}

// CostOriginalGT applies the GT predicate on the "cost_original" field.
func CostOriginalGT(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCostOriginal, v))
}

// CostOriginalGTE applies the GTE predicate on the "cost_original" field.
func CostOriginalGTE(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCostOriginal, v))
}

// CostOriginalLT applies the LT predicate on the "cost_original" field.
func CostOriginalLT(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCostOriginal, v))
}

// CostOriginalLTE applies the LTE predicate on the "cost_original" field.
func CostOriginalLTE(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCostOriginal, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldCurrency, v))
}

// FxRateToCnyEQ applies the EQ predicate on the "fx_rate_to_cny" field.
func FxRateToCnyEQ(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldFxRateToCny, v))
}

// FxRateToCnyNEQ applies the NEQ predicate on the "fx_rate_to_cny" field.
func FxRateToCnyNEQ(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldFxRateToCny, v))
}

// FxRateToCnyIn applies the In predicate on the "fx_rate_to_cny" field.
func FxRateToCnyIn(vs ...float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldFxRateToCny, vs...))
}

// FxRateToCnyNotIn applies the NotIn predicate on the "fx_rate_to_cny" field.
func FxRateToCnyNotIn(vs ...float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldFxRateToCny, vs...))
}

// FxRateToCnyGT applies the GT predicate on the "fx_rate_to_cny" field.
func FxRateToCnyGT(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldFxRateToCny, v))
}

// FxRateToCnyGTE applies the GTE predicate on the "fx_rate_to_cny" field.
func FxRateToCnyGTE(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldFxRateToCny, v))
}

// FxRateToCnyLT applies the LT predicate on the "fx_rate_to_cny" field.
func FxRateToCnyLT(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldFxRateToCny, v))
}

// FxRateToCnyLTE applies the LTE predicate on the "fx_rate_to_cny" field.
func FxRateToCnyLTE(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldFxRateToCny, v))
}

// CostCnyEQ applies the EQ predicate on the "cost_cny" field.
func CostCnyEQ(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldCostCny, v))
}

// CostCnyNEQ applies the NEQ predicate on the "cost_cny" field.
func CostCnyNEQ(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldCostCny, v))
}

// CostCnyIn applies the In predicate on the "cost_cny" field.
func CostCnyIn(vs ...float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldCostCny, vs...))
}

// CostCnyNotIn applies the NotIn predicate on the "cost_cny" field.
func CostCnyNotIn(vs ...float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldCostCny, vs...))
}

// CostCnyGT applies the GT predicate on the "cost_cny" field.
func CostCnyGT(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldCostCny, v))
}

// CostCnyGTE applies the GTE predicate on the "cost_cny" field.
func CostCnyGTE(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldCostCny, v))
}

// CostCnyLT applies the LT predicate on the "cost_cny" field.
func CostCnyLT(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldCostCny, v))
}

// CostCnyLTE applies the LTE predicate on the "cost_cny" field.
func CostCnyLTE(v float64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldCostCny, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldSource, v))
}

// MatchStateEQ applies the EQ predicate on the "match_state" field.
func MatchStateEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchState, v))
}

// MatchStateNEQ applies the NEQ predicate on the "match_state" field.
func MatchStateNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldMatchState, v))
}

// MatchStateIn applies the In predicate on the "match_state" field.
func MatchStateIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldMatchState, vs...))
}

// MatchStateNotIn applies the NotIn predicate on the "match_state" field.
func MatchStateNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldMatchState, vs...))
}

// MatchStateGT applies the GT predicate on the "match_state" field.
func MatchStateGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldMatchState, v))
}

// MatchStateGTE applies the GTE predicate on the "match_state" field.
func MatchStateGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldMatchState, v))
}

// MatchStateLT applies the LT predicate on the "match_state" field.
func MatchStateLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldMatchState, v))
}

// MatchStateLTE applies the LTE predicate on the "match_state" field.
func MatchStateLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldMatchState, v))
}

// MatchStateContains applies the Contains predicate on the "match_state" field.
func MatchStateContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldMatchState, v))
}

// MatchStateHasPrefix applies the HasPrefix predicate on the "match_state" field.
func MatchStateHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldMatchState, v))
}

// MatchStateHasSuffix applies the HasSuffix predicate on the "match_state" field.
func MatchStateHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldMatchState, v))
}

// MatchStateEqualFold applies the EqualFold predicate on the "match_state" field.
func MatchStateEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldMatchState, v))
}

// MatchStateContainsFold applies the ContainsFold predicate on the "match_state" field.
func MatchStateContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldMatchState, v))
}

// MatchMethodEQ applies the EQ predicate on the "match_method" field.
func MatchMethodEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchMethod, v))
}

// MatchMethodNEQ applies the NEQ predicate on the "match_method" field.
func MatchMethodNEQ(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldMatchMethod, v))
}

// MatchMethodIn applies the In predicate on the "match_method" field.
func MatchMethodIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldMatchMethod, vs...))
}

// MatchMethodNotIn applies the NotIn predicate on the "match_method" field.
func MatchMethodNotIn(vs ...string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldMatchMethod, vs...))
}

// MatchMethodGT applies the GT predicate on the "match_method" field.
func MatchMethodGT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldMatchMethod, v))
}

// MatchMethodGTE applies the GTE predicate on the "match_method" field.
func MatchMethodGTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldMatchMethod, v))
}

// MatchMethodLT applies the LT predicate on the "match_method" field.
func MatchMethodLT(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldMatchMethod, v))
}

// MatchMethodLTE applies the LTE predicate on the "match_method" field.
func MatchMethodLTE(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldMatchMethod, v))
}

// MatchMethodContains applies the Contains predicate on the "match_method" field.
func MatchMethodContains(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContains(FieldMatchMethod, v))
}

// MatchMethodHasPrefix applies the HasPrefix predicate on the "match_method" field.
func MatchMethodHasPrefix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasPrefix(FieldMatchMethod, v))
}

// MatchMethodHasSuffix applies the HasSuffix predicate on the "match_method" field.
func MatchMethodHasSuffix(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldHasSuffix(FieldMatchMethod, v))
}

// MatchMethodEqualFold applies the EqualFold predicate on the "match_method" field.
func MatchMethodEqualFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEqualFold(FieldMatchMethod, v))
}

// MatchMethodContainsFold applies the ContainsFold predicate on the "match_method" field.
func MatchMethodContainsFold(v string) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldContainsFold(FieldMatchMethod, v))
}

// MatchedUsageLogIDEQ applies the EQ predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDEQ(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchedUsageLogID, v))
}

// MatchedUsageLogIDNEQ applies the NEQ predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDNEQ(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldMatchedUsageLogID, v))
}

// MatchedUsageLogIDIn applies the In predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDIn(vs ...int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldMatchedUsageLogID, vs...))
}

// MatchedUsageLogIDNotIn applies the NotIn predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDNotIn(vs ...int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldMatchedUsageLogID, vs...))
}

// MatchedUsageLogIDGT applies the GT predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDGT(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldMatchedUsageLogID, v))
}

// MatchedUsageLogIDGTE applies the GTE predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDGTE(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldMatchedUsageLogID, v))
}

// MatchedUsageLogIDLT applies the LT predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDLT(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldMatchedUsageLogID, v))
}

// MatchedUsageLogIDLTE applies the LTE predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDLTE(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldMatchedUsageLogID, v))
}

// MatchedUsageLogIDIsNil applies the IsNil predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDIsNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIsNull(FieldMatchedUsageLogID))
}

// MatchedUsageLogIDNotNil applies the NotNil predicate on the "matched_usage_log_id" field.
func MatchedUsageLogIDNotNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotNull(FieldMatchedUsageLogID))
}

// MatchedAccountIDEQ applies the EQ predicate on the "matched_account_id" field.
func MatchedAccountIDEQ(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldMatchedAccountID, v))
}

// MatchedAccountIDNEQ applies the NEQ predicate on the "matched_account_id" field.
func MatchedAccountIDNEQ(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldMatchedAccountID, v))
}

// MatchedAccountIDIn applies the In predicate on the "matched_account_id" field.
func MatchedAccountIDIn(vs ...int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldMatchedAccountID, vs...))
}

// MatchedAccountIDNotIn applies the NotIn predicate on the "matched_account_id" field.
func MatchedAccountIDNotIn(vs ...int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldMatchedAccountID, vs...))
}

// MatchedAccountIDGT applies the GT predicate on the "matched_account_id" field.
func MatchedAccountIDGT(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldMatchedAccountID, v))
}

// MatchedAccountIDGTE applies the GTE predicate on the "matched_account_id" field.
func MatchedAccountIDGTE(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldMatchedAccountID, v))
}

// MatchedAccountIDLT applies the LT predicate on the "matched_account_id" field.
func MatchedAccountIDLT(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldMatchedAccountID, v))
}

// MatchedAccountIDLTE applies the LTE predicate on the "matched_account_id" field.
func MatchedAccountIDLTE(v int64) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldMatchedAccountID, v))
}

// MatchedAccountIDIsNil applies the IsNil predicate on the "matched_account_id" field.
func MatchedAccountIDIsNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIsNull(FieldMatchedAccountID))
}

// MatchedAccountIDNotNil applies the NotNil predicate on the "matched_account_id" field.
func MatchedAccountIDNotNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotNull(FieldMatchedAccountID))
}

// RawIsNil applies the IsNil predicate on the "raw" field.
func RawIsNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIsNull(FieldRaw))
}

// RawNotNil applies the NotNil predicate on the "raw" field.
func RawNotNil() predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotNull(FieldRaw))
}

// ImportedAtEQ applies the EQ predicate on the "imported_at" field.
func ImportedAtEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldEQ(FieldImportedAt, v))
}

// ImportedAtNEQ applies the NEQ predicate on the "imported_at" field.
func ImportedAtNEQ(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNEQ(FieldImportedAt, v))
}

// ImportedAtIn applies the In predicate on the "imported_at" field.
func ImportedAtIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldIn(FieldImportedAt, vs...))
}

// ImportedAtNotIn applies the NotIn predicate on the "imported_at" field.
func ImportedAtNotIn(vs ...time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldNotIn(FieldImportedAt, vs...))
}

// ImportedAtGT applies the GT predicate on the "imported_at" field.
func ImportedAtGT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGT(FieldImportedAt, v))
}

// ImportedAtGTE applies the GTE predicate on the "imported_at" field.
func ImportedAtGTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldGTE(FieldImportedAt, v))
}

// ImportedAtLT applies the LT predicate on the "imported_at" field.
func ImportedAtLT(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLT(FieldImportedAt, v))
}

// ImportedAtLTE applies the LTE predicate on the "imported_at" field.
func ImportedAtLTE(v time.Time) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.FieldLTE(FieldImportedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReconciliationUpstreamBill) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReconciliationUpstreamBill) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReconciliationUpstreamBill) predicate.ReconciliationUpstreamBill {
	return predicate.ReconciliationUpstreamBill(sql.NotPredicates(p))
}
